#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmssSync
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RMSS20140825")]
	public partial class DataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataClassDataContext() : 
				base(global::RmssSync.Properties.Settings.Default.RMSS20140825ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClientTypeA> ClientTypeA
		{
			get
			{
				return this.GetTable<ClientTypeA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientTypeA")]
	public partial class ClientTypeA
	{
		
		private string _SUBSCRIBERNO;
		
		private string _DESCRIPTION;
		
		private string _CUSTOMER_NO;
		
		private string _CUSTTYPE;
		
		private string _LINKMAN;
		
		private string _EMAIL;
		
		private string _MOBILE_NO;
		
		private string _PHONE_NO;
		
		private string _FAX_NO;
		
		private string _ZIP_CODE;
		
		private string _ADDRESS;
		
		private string _TYPE;
		
		private string _REMARK;
		
		private System.Nullable<decimal> _CUSTOMER_LEVEL;
		
		private string _SALE_NAME;
		
		public ClientTypeA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBSCRIBERNO", DbType="VarChar(256)")]
		public string SUBSCRIBERNO
		{
			get
			{
				return this._SUBSCRIBERNO;
			}
			set
			{
				if ((this._SUBSCRIBERNO != value))
				{
					this._SUBSCRIBERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(256)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NO", DbType="VarChar(63) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NO
		{
			get
			{
				return this._CUSTOMER_NO;
			}
			set
			{
				if ((this._CUSTOMER_NO != value))
				{
					this._CUSTOMER_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTTYPE", DbType="VarChar(64)")]
		public string CUSTTYPE
		{
			get
			{
				return this._CUSTTYPE;
			}
			set
			{
				if ((this._CUSTTYPE != value))
				{
					this._CUSTTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINKMAN", DbType="VarChar(63)")]
		public string LINKMAN
		{
			get
			{
				return this._LINKMAN;
			}
			set
			{
				if ((this._LINKMAN != value))
				{
					this._LINKMAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(30)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE_NO", DbType="VarChar(64)")]
		public string MOBILE_NO
		{
			get
			{
				return this._MOBILE_NO;
			}
			set
			{
				if ((this._MOBILE_NO != value))
				{
					this._MOBILE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NO", DbType="VarChar(129)")]
		public string PHONE_NO
		{
			get
			{
				return this._PHONE_NO;
			}
			set
			{
				if ((this._PHONE_NO != value))
				{
					this._PHONE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX_NO", DbType="VarChar(64)")]
		public string FAX_NO
		{
			get
			{
				return this._FAX_NO;
			}
			set
			{
				if ((this._FAX_NO != value))
				{
					this._FAX_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP_CODE", DbType="VarChar(6)")]
		public string ZIP_CODE
		{
			get
			{
				return this._ZIP_CODE;
			}
			set
			{
				if ((this._ZIP_CODE != value))
				{
					this._ZIP_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(704)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(100)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(100)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this._REMARK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_LEVEL", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> CUSTOMER_LEVEL
		{
			get
			{
				return this._CUSTOMER_LEVEL;
			}
			set
			{
				if ((this._CUSTOMER_LEVEL != value))
				{
					this._CUSTOMER_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME", DbType="VarChar(64)")]
		public string SALE_NAME
		{
			get
			{
				return this._SALE_NAME;
			}
			set
			{
				if ((this._SALE_NAME != value))
				{
					this._SALE_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
