#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="RMSS")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertIP_Bussiness(IP_Bussiness instance);
  partial void UpdateIP_Bussiness(IP_Bussiness instance);
  partial void DeleteIP_Bussiness(IP_Bussiness instance);
  partial void InsertJrlx_List(Jrlx_List instance);
  partial void UpdateJrlx_List(Jrlx_List instance);
  partial void DeleteJrlx_List(Jrlx_List instance);
  partial void InsertAssemblyPortSource_Details(AssemblyPortSource_Details instance);
  partial void UpdateAssemblyPortSource_Details(AssemblyPortSource_Details instance);
  partial void DeleteAssemblyPortSource_Details(AssemblyPortSource_Details instance);
  partial void InsertONU_Dk(ONU_Dk instance);
  partial void UpdateONU_Dk(ONU_Dk instance);
  partial void DeleteONU_Dk(ONU_Dk instance);
  partial void InsertYwONU_glb(YwONU_glb instance);
  partial void UpdateYwONU_glb(YwONU_glb instance);
  partial void DeleteYwONU_glb(YwONU_glb instance);
  partial void InsertVlan_Distribute(Vlan_Distribute instance);
  partial void UpdateVlan_Distribute(Vlan_Distribute instance);
  partial void DeleteVlan_Distribute(Vlan_Distribute instance);
  partial void Insertts_kh(ts_kh instance);
  partial void Updatets_kh(ts_kh instance);
  partial void Deletets_kh(ts_kh instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RMSSConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<IP_Bussiness> IP_Bussiness
	{
		get
		{
			return this.GetTable<IP_Bussiness>();
		}
	}
	
	public System.Data.Linq.Table<TS_ZD_Info> TS_ZD_Info
	{
		get
		{
			return this.GetTable<TS_ZD_Info>();
		}
	}
	
	public System.Data.Linq.Table<Jrlx_List> Jrlx_List
	{
		get
		{
			return this.GetTable<Jrlx_List>();
		}
	}
	
	public System.Data.Linq.Table<AssemblyPortSource_Master> AssemblyPortSource_Master
	{
		get
		{
			return this.GetTable<AssemblyPortSource_Master>();
		}
	}
	
	public System.Data.Linq.Table<AssemblyPortSource_Details> AssemblyPortSource_Details
	{
		get
		{
			return this.GetTable<AssemblyPortSource_Details>();
		}
	}
	
	public System.Data.Linq.Table<ONU_Dk> ONU_Dk
	{
		get
		{
			return this.GetTable<ONU_Dk>();
		}
	}
	
	public System.Data.Linq.Table<YwONU_glb> YwONU_glb
	{
		get
		{
			return this.GetTable<YwONU_glb>();
		}
	}
	
	public System.Data.Linq.Table<Vlan_Distribute> Vlan_Distribute
	{
		get
		{
			return this.GetTable<Vlan_Distribute>();
		}
	}
	
	public System.Data.Linq.Table<ts_kh> ts_kh
	{
		get
		{
			return this.GetTable<ts_kh>();
		}
	}
}

[Table(Name="dbo.IP_Bussiness")]
public partial class IP_Bussiness : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _ID;
	
	private string _Bussiness_code;
	
	private string _Line_code;
	
	private string _jrsb;
	
	private string _sbbh;
	
	private string _sbmc;
	
	private string _xqjrwg;
	
	private string _ywlx;
	
	private string _khbh;
	
	private string _khmc;
	
	private string _khlxr;
	
	private string _lxdh;
	
	private string _khlx;
	
	private string _fgqdk;
	
	private string _VPN;
	
	private string _gcjx;
	
	private string _gqtx;
	
	private string _gsfq;
	
	private string _gsfqdk;
	
	private string _sfqxh;
	
	private string _ht_VPN;
	
	private string _VLAN;
	
	private string _brandwidth;
	
	private string _remark;
	
	private string _by1;
	
	private System.Nullable<int> _state;
	
	private string _pzr;
	
	private string _pzsj;
	
	private string _khdz;
	
	private string _jrlyq;
	
	private string _jrjhj;
	
	private string _jrjhjdk;
	
	private string _jrdmc;
	
	private string _yhzyipwg;
	
	private string _yhlywd;
	
	private string _VLAN_name;
	
	private string _dksl;
	
	private string _gqsfqdk;
	
	private string _jrlyqdk;
	
	private string _yhlyqdz;
	
	private string _VPN_Name;
	
	private string _jrdk;
	
	private string _maconu;
	
	private string _dldw;
	
	private string _jfipdz;
	
	private string _voipgw;
	
	private string _pvcid;
	
	private string _bdjfvlan;
	
	private string _ddjfvlan;
	
	private string _ddsbbh;
	
	private string _ddsbmc;
	
	private string _ddsbdk;
	
	private string _macid;
	
	private string _dd_macid;
	
	private string _sbpzxx;
	
	private string _Sbdkhid;
	
	private string _ddsbdkhid;
	
	private string _gjsj;
	
	private string _gjremark;
	
	private string _LjjfID;
	
	private string _DdLjjfID;
	
	private string _Ssqy;
	
	private System.Nullable<long> _Csts;
	
	private string _Cjr;
	
	private string _Cjrq;
	
	private string _Cssj;
	
	private string _issend;
	
	private string _OUNdk_Dd;
	
	private string _glYwONULsh;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnBussiness_codeChanging(string value);
    partial void OnBussiness_codeChanged();
    partial void OnLine_codeChanging(string value);
    partial void OnLine_codeChanged();
    partial void OnjrsbChanging(string value);
    partial void OnjrsbChanged();
    partial void OnsbbhChanging(string value);
    partial void OnsbbhChanged();
    partial void OnsbmcChanging(string value);
    partial void OnsbmcChanged();
    partial void OnxqjrwgChanging(string value);
    partial void OnxqjrwgChanged();
    partial void OnywlxChanging(string value);
    partial void OnywlxChanged();
    partial void OnkhbhChanging(string value);
    partial void OnkhbhChanged();
    partial void OnkhmcChanging(string value);
    partial void OnkhmcChanged();
    partial void OnkhlxrChanging(string value);
    partial void OnkhlxrChanged();
    partial void OnlxdhChanging(string value);
    partial void OnlxdhChanged();
    partial void OnkhlxChanging(string value);
    partial void OnkhlxChanged();
    partial void OnfgqdkChanging(string value);
    partial void OnfgqdkChanged();
    partial void OnVPNChanging(string value);
    partial void OnVPNChanged();
    partial void OngcjxChanging(string value);
    partial void OngcjxChanged();
    partial void OngqtxChanging(string value);
    partial void OngqtxChanged();
    partial void OngsfqChanging(string value);
    partial void OngsfqChanged();
    partial void OngsfqdkChanging(string value);
    partial void OngsfqdkChanged();
    partial void OnsfqxhChanging(string value);
    partial void OnsfqxhChanged();
    partial void Onht_VPNChanging(string value);
    partial void Onht_VPNChanged();
    partial void OnVLANChanging(string value);
    partial void OnVLANChanged();
    partial void OnbrandwidthChanging(string value);
    partial void OnbrandwidthChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void Onby1Changing(string value);
    partial void Onby1Changed();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    partial void OnpzrChanging(string value);
    partial void OnpzrChanged();
    partial void OnpzsjChanging(string value);
    partial void OnpzsjChanged();
    partial void OnkhdzChanging(string value);
    partial void OnkhdzChanged();
    partial void OnjrlyqChanging(string value);
    partial void OnjrlyqChanged();
    partial void OnjrjhjChanging(string value);
    partial void OnjrjhjChanged();
    partial void OnjrjhjdkChanging(string value);
    partial void OnjrjhjdkChanged();
    partial void OnjrdmcChanging(string value);
    partial void OnjrdmcChanged();
    partial void OnyhzyipwgChanging(string value);
    partial void OnyhzyipwgChanged();
    partial void OnyhlywdChanging(string value);
    partial void OnyhlywdChanged();
    partial void OnVLAN_nameChanging(string value);
    partial void OnVLAN_nameChanged();
    partial void OndkslChanging(string value);
    partial void OndkslChanged();
    partial void OngqsfqdkChanging(string value);
    partial void OngqsfqdkChanged();
    partial void OnjrlyqdkChanging(string value);
    partial void OnjrlyqdkChanged();
    partial void OnyhlyqdzChanging(string value);
    partial void OnyhlyqdzChanged();
    partial void OnVPN_NameChanging(string value);
    partial void OnVPN_NameChanged();
    partial void OnjrdkChanging(string value);
    partial void OnjrdkChanged();
    partial void OnmaconuChanging(string value);
    partial void OnmaconuChanged();
    partial void OndldwChanging(string value);
    partial void OndldwChanged();
    partial void OnjfipdzChanging(string value);
    partial void OnjfipdzChanged();
    partial void OnvoipgwChanging(string value);
    partial void OnvoipgwChanged();
    partial void OnpvcidChanging(string value);
    partial void OnpvcidChanged();
    partial void OnbdjfvlanChanging(string value);
    partial void OnbdjfvlanChanged();
    partial void OnddjfvlanChanging(string value);
    partial void OnddjfvlanChanged();
    partial void OnddsbbhChanging(string value);
    partial void OnddsbbhChanged();
    partial void OnddsbmcChanging(string value);
    partial void OnddsbmcChanged();
    partial void OnddsbdkChanging(string value);
    partial void OnddsbdkChanged();
    partial void OnmacidChanging(string value);
    partial void OnmacidChanged();
    partial void Ondd_macidChanging(string value);
    partial void Ondd_macidChanged();
    partial void OnsbpzxxChanging(string value);
    partial void OnsbpzxxChanged();
    partial void OnSbdkhidChanging(string value);
    partial void OnSbdkhidChanged();
    partial void OnddsbdkhidChanging(string value);
    partial void OnddsbdkhidChanged();
    partial void OngjsjChanging(string value);
    partial void OngjsjChanged();
    partial void OngjremarkChanging(string value);
    partial void OngjremarkChanged();
    partial void OnLjjfIDChanging(string value);
    partial void OnLjjfIDChanged();
    partial void OnDdLjjfIDChanging(string value);
    partial void OnDdLjjfIDChanged();
    partial void OnSsqyChanging(string value);
    partial void OnSsqyChanged();
    partial void OnCstsChanging(System.Nullable<long> value);
    partial void OnCstsChanged();
    partial void OnCjrChanging(string value);
    partial void OnCjrChanged();
    partial void OnCjrqChanging(string value);
    partial void OnCjrqChanged();
    partial void OnCssjChanging(string value);
    partial void OnCssjChanged();
    partial void OnissendChanging(string value);
    partial void OnissendChanged();
    partial void OnOUNdk_DdChanging(string value);
    partial void OnOUNdk_DdChanged();
    partial void OnglYwONULshChanging(string value);
    partial void OnglYwONULshChanged();
    #endregion
	
	public IP_Bussiness()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_Bussiness_code", DbType="NVarChar(100)")]
	public string Bussiness_code
	{
		get
		{
			return this._Bussiness_code;
		}
		set
		{
			if ((this._Bussiness_code != value))
			{
				this.OnBussiness_codeChanging(value);
				this.SendPropertyChanging();
				this._Bussiness_code = value;
				this.SendPropertyChanged("Bussiness_code");
				this.OnBussiness_codeChanged();
			}
		}
	}
	
	[Column(Storage="_Line_code", DbType="VarChar(50)")]
	public string Line_code
	{
		get
		{
			return this._Line_code;
		}
		set
		{
			if ((this._Line_code != value))
			{
				this.OnLine_codeChanging(value);
				this.SendPropertyChanging();
				this._Line_code = value;
				this.SendPropertyChanged("Line_code");
				this.OnLine_codeChanged();
			}
		}
	}
	
	[Column(Storage="_jrsb", DbType="VarChar(50)")]
	public string jrsb
	{
		get
		{
			return this._jrsb;
		}
		set
		{
			if ((this._jrsb != value))
			{
				this.OnjrsbChanging(value);
				this.SendPropertyChanging();
				this._jrsb = value;
				this.SendPropertyChanged("jrsb");
				this.OnjrsbChanged();
			}
		}
	}
	
	[Column(Storage="_sbbh", DbType="VarChar(50)")]
	public string sbbh
	{
		get
		{
			return this._sbbh;
		}
		set
		{
			if ((this._sbbh != value))
			{
				this.OnsbbhChanging(value);
				this.SendPropertyChanging();
				this._sbbh = value;
				this.SendPropertyChanged("sbbh");
				this.OnsbbhChanged();
			}
		}
	}
	
	[Column(Storage="_sbmc", DbType="NVarChar(50)")]
	public string sbmc
	{
		get
		{
			return this._sbmc;
		}
		set
		{
			if ((this._sbmc != value))
			{
				this.OnsbmcChanging(value);
				this.SendPropertyChanging();
				this._sbmc = value;
				this.SendPropertyChanged("sbmc");
				this.OnsbmcChanged();
			}
		}
	}
	
	[Column(Storage="_xqjrwg", DbType="VarChar(50)")]
	public string xqjrwg
	{
		get
		{
			return this._xqjrwg;
		}
		set
		{
			if ((this._xqjrwg != value))
			{
				this.OnxqjrwgChanging(value);
				this.SendPropertyChanging();
				this._xqjrwg = value;
				this.SendPropertyChanged("xqjrwg");
				this.OnxqjrwgChanged();
			}
		}
	}
	
	[Column(Storage="_ywlx", DbType="VarChar(50)")]
	public string ywlx
	{
		get
		{
			return this._ywlx;
		}
		set
		{
			if ((this._ywlx != value))
			{
				this.OnywlxChanging(value);
				this.SendPropertyChanging();
				this._ywlx = value;
				this.SendPropertyChanged("ywlx");
				this.OnywlxChanged();
			}
		}
	}
	
	[Column(Storage="_khbh", DbType="VarChar(50)")]
	public string khbh
	{
		get
		{
			return this._khbh;
		}
		set
		{
			if ((this._khbh != value))
			{
				this.OnkhbhChanging(value);
				this.SendPropertyChanging();
				this._khbh = value;
				this.SendPropertyChanged("khbh");
				this.OnkhbhChanged();
			}
		}
	}
	
	[Column(Storage="_khmc", DbType="VarChar(200)")]
	public string khmc
	{
		get
		{
			return this._khmc;
		}
		set
		{
			if ((this._khmc != value))
			{
				this.OnkhmcChanging(value);
				this.SendPropertyChanging();
				this._khmc = value;
				this.SendPropertyChanged("khmc");
				this.OnkhmcChanged();
			}
		}
	}
	
	[Column(Storage="_khlxr", DbType="VarChar(100)")]
	public string khlxr
	{
		get
		{
			return this._khlxr;
		}
		set
		{
			if ((this._khlxr != value))
			{
				this.OnkhlxrChanging(value);
				this.SendPropertyChanging();
				this._khlxr = value;
				this.SendPropertyChanged("khlxr");
				this.OnkhlxrChanged();
			}
		}
	}
	
	[Column(Storage="_lxdh", DbType="VarChar(100)")]
	public string lxdh
	{
		get
		{
			return this._lxdh;
		}
		set
		{
			if ((this._lxdh != value))
			{
				this.OnlxdhChanging(value);
				this.SendPropertyChanging();
				this._lxdh = value;
				this.SendPropertyChanged("lxdh");
				this.OnlxdhChanged();
			}
		}
	}
	
	[Column(Storage="_khlx", DbType="VarChar(50)")]
	public string khlx
	{
		get
		{
			return this._khlx;
		}
		set
		{
			if ((this._khlx != value))
			{
				this.OnkhlxChanging(value);
				this.SendPropertyChanging();
				this._khlx = value;
				this.SendPropertyChanged("khlx");
				this.OnkhlxChanged();
			}
		}
	}
	
	[Column(Storage="_fgqdk", DbType="VarChar(20)")]
	public string fgqdk
	{
		get
		{
			return this._fgqdk;
		}
		set
		{
			if ((this._fgqdk != value))
			{
				this.OnfgqdkChanging(value);
				this.SendPropertyChanging();
				this._fgqdk = value;
				this.SendPropertyChanged("fgqdk");
				this.OnfgqdkChanged();
			}
		}
	}
	
	[Column(Storage="_VPN", DbType="VarChar(50)")]
	public string VPN
	{
		get
		{
			return this._VPN;
		}
		set
		{
			if ((this._VPN != value))
			{
				this.OnVPNChanging(value);
				this.SendPropertyChanging();
				this._VPN = value;
				this.SendPropertyChanged("VPN");
				this.OnVPNChanged();
			}
		}
	}
	
	[Column(Storage="_gcjx", DbType="VarChar(50)")]
	public string gcjx
	{
		get
		{
			return this._gcjx;
		}
		set
		{
			if ((this._gcjx != value))
			{
				this.OngcjxChanging(value);
				this.SendPropertyChanging();
				this._gcjx = value;
				this.SendPropertyChanged("gcjx");
				this.OngcjxChanged();
			}
		}
	}
	
	[Column(Storage="_gqtx", DbType="VarChar(100)")]
	public string gqtx
	{
		get
		{
			return this._gqtx;
		}
		set
		{
			if ((this._gqtx != value))
			{
				this.OngqtxChanging(value);
				this.SendPropertyChanging();
				this._gqtx = value;
				this.SendPropertyChanged("gqtx");
				this.OngqtxChanged();
			}
		}
	}
	
	[Column(Storage="_gsfq", DbType="VarChar(50)")]
	public string gsfq
	{
		get
		{
			return this._gsfq;
		}
		set
		{
			if ((this._gsfq != value))
			{
				this.OngsfqChanging(value);
				this.SendPropertyChanging();
				this._gsfq = value;
				this.SendPropertyChanged("gsfq");
				this.OngsfqChanged();
			}
		}
	}
	
	[Column(Storage="_gsfqdk", DbType="VarChar(50)")]
	public string gsfqdk
	{
		get
		{
			return this._gsfqdk;
		}
		set
		{
			if ((this._gsfqdk != value))
			{
				this.OngsfqdkChanging(value);
				this.SendPropertyChanging();
				this._gsfqdk = value;
				this.SendPropertyChanged("gsfqdk");
				this.OngsfqdkChanged();
			}
		}
	}
	
	[Column(Storage="_sfqxh", DbType="VarChar(50)")]
	public string sfqxh
	{
		get
		{
			return this._sfqxh;
		}
		set
		{
			if ((this._sfqxh != value))
			{
				this.OnsfqxhChanging(value);
				this.SendPropertyChanging();
				this._sfqxh = value;
				this.SendPropertyChanged("sfqxh");
				this.OnsfqxhChanged();
			}
		}
	}
	
	[Column(Storage="_ht_VPN", DbType="VarChar(100)")]
	public string ht_VPN
	{
		get
		{
			return this._ht_VPN;
		}
		set
		{
			if ((this._ht_VPN != value))
			{
				this.Onht_VPNChanging(value);
				this.SendPropertyChanging();
				this._ht_VPN = value;
				this.SendPropertyChanged("ht_VPN");
				this.Onht_VPNChanged();
			}
		}
	}
	
	[Column(Storage="_VLAN", DbType="VarChar(50)")]
	public string VLAN
	{
		get
		{
			return this._VLAN;
		}
		set
		{
			if ((this._VLAN != value))
			{
				this.OnVLANChanging(value);
				this.SendPropertyChanging();
				this._VLAN = value;
				this.SendPropertyChanged("VLAN");
				this.OnVLANChanged();
			}
		}
	}
	
	[Column(Storage="_brandwidth", DbType="VarChar(50)")]
	public string brandwidth
	{
		get
		{
			return this._brandwidth;
		}
		set
		{
			if ((this._brandwidth != value))
			{
				this.OnbrandwidthChanging(value);
				this.SendPropertyChanging();
				this._brandwidth = value;
				this.SendPropertyChanged("brandwidth");
				this.OnbrandwidthChanged();
			}
		}
	}
	
	[Column(Storage="_remark", DbType="VarChar(8000)")]
	public string remark
	{
		get
		{
			return this._remark;
		}
		set
		{
			if ((this._remark != value))
			{
				this.OnremarkChanging(value);
				this.SendPropertyChanging();
				this._remark = value;
				this.SendPropertyChanged("remark");
				this.OnremarkChanged();
			}
		}
	}
	
	[Column(Storage="_by1", DbType="VarChar(200)")]
	public string by1
	{
		get
		{
			return this._by1;
		}
		set
		{
			if ((this._by1 != value))
			{
				this.Onby1Changing(value);
				this.SendPropertyChanging();
				this._by1 = value;
				this.SendPropertyChanged("by1");
				this.Onby1Changed();
			}
		}
	}
	
	[Column(Storage="_state", DbType="Int")]
	public System.Nullable<int> state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[Column(Storage="_pzr", DbType="VarChar(50)")]
	public string pzr
	{
		get
		{
			return this._pzr;
		}
		set
		{
			if ((this._pzr != value))
			{
				this.OnpzrChanging(value);
				this.SendPropertyChanging();
				this._pzr = value;
				this.SendPropertyChanged("pzr");
				this.OnpzrChanged();
			}
		}
	}
	
	[Column(Storage="_pzsj", DbType="VarChar(10)")]
	public string pzsj
	{
		get
		{
			return this._pzsj;
		}
		set
		{
			if ((this._pzsj != value))
			{
				this.OnpzsjChanging(value);
				this.SendPropertyChanging();
				this._pzsj = value;
				this.SendPropertyChanged("pzsj");
				this.OnpzsjChanged();
			}
		}
	}
	
	[Column(Storage="_khdz", DbType="NVarChar(100)")]
	public string khdz
	{
		get
		{
			return this._khdz;
		}
		set
		{
			if ((this._khdz != value))
			{
				this.OnkhdzChanging(value);
				this.SendPropertyChanging();
				this._khdz = value;
				this.SendPropertyChanged("khdz");
				this.OnkhdzChanged();
			}
		}
	}
	
	[Column(Storage="_jrlyq", DbType="VarChar(50)")]
	public string jrlyq
	{
		get
		{
			return this._jrlyq;
		}
		set
		{
			if ((this._jrlyq != value))
			{
				this.OnjrlyqChanging(value);
				this.SendPropertyChanging();
				this._jrlyq = value;
				this.SendPropertyChanged("jrlyq");
				this.OnjrlyqChanged();
			}
		}
	}
	
	[Column(Storage="_jrjhj", DbType="VarChar(50)")]
	public string jrjhj
	{
		get
		{
			return this._jrjhj;
		}
		set
		{
			if ((this._jrjhj != value))
			{
				this.OnjrjhjChanging(value);
				this.SendPropertyChanging();
				this._jrjhj = value;
				this.SendPropertyChanged("jrjhj");
				this.OnjrjhjChanged();
			}
		}
	}
	
	[Column(Storage="_jrjhjdk", DbType="VarChar(50)")]
	public string jrjhjdk
	{
		get
		{
			return this._jrjhjdk;
		}
		set
		{
			if ((this._jrjhjdk != value))
			{
				this.OnjrjhjdkChanging(value);
				this.SendPropertyChanging();
				this._jrjhjdk = value;
				this.SendPropertyChanged("jrjhjdk");
				this.OnjrjhjdkChanged();
			}
		}
	}
	
	[Column(Storage="_jrdmc", DbType="NVarChar(100)")]
	public string jrdmc
	{
		get
		{
			return this._jrdmc;
		}
		set
		{
			if ((this._jrdmc != value))
			{
				this.OnjrdmcChanging(value);
				this.SendPropertyChanging();
				this._jrdmc = value;
				this.SendPropertyChanged("jrdmc");
				this.OnjrdmcChanged();
			}
		}
	}
	
	[Column(Storage="_yhzyipwg", DbType="VarChar(1000)")]
	public string yhzyipwg
	{
		get
		{
			return this._yhzyipwg;
		}
		set
		{
			if ((this._yhzyipwg != value))
			{
				this.OnyhzyipwgChanging(value);
				this.SendPropertyChanging();
				this._yhzyipwg = value;
				this.SendPropertyChanged("yhzyipwg");
				this.OnyhzyipwgChanged();
			}
		}
	}
	
	[Column(Storage="_yhlywd", DbType="VarChar(225)")]
	public string yhlywd
	{
		get
		{
			return this._yhlywd;
		}
		set
		{
			if ((this._yhlywd != value))
			{
				this.OnyhlywdChanging(value);
				this.SendPropertyChanging();
				this._yhlywd = value;
				this.SendPropertyChanged("yhlywd");
				this.OnyhlywdChanged();
			}
		}
	}
	
	[Column(Storage="_VLAN_name", DbType="VarChar(50)")]
	public string VLAN_name
	{
		get
		{
			return this._VLAN_name;
		}
		set
		{
			if ((this._VLAN_name != value))
			{
				this.OnVLAN_nameChanging(value);
				this.SendPropertyChanging();
				this._VLAN_name = value;
				this.SendPropertyChanged("VLAN_name");
				this.OnVLAN_nameChanged();
			}
		}
	}
	
	[Column(Storage="_dksl", DbType="VarChar(50)")]
	public string dksl
	{
		get
		{
			return this._dksl;
		}
		set
		{
			if ((this._dksl != value))
			{
				this.OndkslChanging(value);
				this.SendPropertyChanging();
				this._dksl = value;
				this.SendPropertyChanged("dksl");
				this.OndkslChanged();
			}
		}
	}
	
	[Column(Storage="_gqsfqdk", DbType="VarChar(50)")]
	public string gqsfqdk
	{
		get
		{
			return this._gqsfqdk;
		}
		set
		{
			if ((this._gqsfqdk != value))
			{
				this.OngqsfqdkChanging(value);
				this.SendPropertyChanging();
				this._gqsfqdk = value;
				this.SendPropertyChanged("gqsfqdk");
				this.OngqsfqdkChanged();
			}
		}
	}
	
	[Column(Storage="_jrlyqdk", DbType="VarChar(50)")]
	public string jrlyqdk
	{
		get
		{
			return this._jrlyqdk;
		}
		set
		{
			if ((this._jrlyqdk != value))
			{
				this.OnjrlyqdkChanging(value);
				this.SendPropertyChanging();
				this._jrlyqdk = value;
				this.SendPropertyChanged("jrlyqdk");
				this.OnjrlyqdkChanged();
			}
		}
	}
	
	[Column(Storage="_yhlyqdz", DbType="VarChar(50)")]
	public string yhlyqdz
	{
		get
		{
			return this._yhlyqdz;
		}
		set
		{
			if ((this._yhlyqdz != value))
			{
				this.OnyhlyqdzChanging(value);
				this.SendPropertyChanging();
				this._yhlyqdz = value;
				this.SendPropertyChanged("yhlyqdz");
				this.OnyhlyqdzChanged();
			}
		}
	}
	
	[Column(Storage="_VPN_Name", DbType="VarChar(50)")]
	public string VPN_Name
	{
		get
		{
			return this._VPN_Name;
		}
		set
		{
			if ((this._VPN_Name != value))
			{
				this.OnVPN_NameChanging(value);
				this.SendPropertyChanging();
				this._VPN_Name = value;
				this.SendPropertyChanged("VPN_Name");
				this.OnVPN_NameChanged();
			}
		}
	}
	
	[Column(Storage="_jrdk", DbType="VarChar(50)")]
	public string jrdk
	{
		get
		{
			return this._jrdk;
		}
		set
		{
			if ((this._jrdk != value))
			{
				this.OnjrdkChanging(value);
				this.SendPropertyChanging();
				this._jrdk = value;
				this.SendPropertyChanged("jrdk");
				this.OnjrdkChanged();
			}
		}
	}
	
	[Column(Storage="_maconu", DbType="NVarChar(50)")]
	public string maconu
	{
		get
		{
			return this._maconu;
		}
		set
		{
			if ((this._maconu != value))
			{
				this.OnmaconuChanging(value);
				this.SendPropertyChanging();
				this._maconu = value;
				this.SendPropertyChanged("maconu");
				this.OnmaconuChanged();
			}
		}
	}
	
	[Column(Storage="_dldw", DbType="NVarChar(100)")]
	public string dldw
	{
		get
		{
			return this._dldw;
		}
		set
		{
			if ((this._dldw != value))
			{
				this.OndldwChanging(value);
				this.SendPropertyChanging();
				this._dldw = value;
				this.SendPropertyChanged("dldw");
				this.OndldwChanged();
			}
		}
	}
	
	[Column(Storage="_jfipdz", DbType="VarChar(300)")]
	public string jfipdz
	{
		get
		{
			return this._jfipdz;
		}
		set
		{
			if ((this._jfipdz != value))
			{
				this.OnjfipdzChanging(value);
				this.SendPropertyChanging();
				this._jfipdz = value;
				this.SendPropertyChanged("jfipdz");
				this.OnjfipdzChanged();
			}
		}
	}
	
	[Column(Storage="_voipgw", DbType="VarChar(300)")]
	public string voipgw
	{
		get
		{
			return this._voipgw;
		}
		set
		{
			if ((this._voipgw != value))
			{
				this.OnvoipgwChanging(value);
				this.SendPropertyChanging();
				this._voipgw = value;
				this.SendPropertyChanged("voipgw");
				this.OnvoipgwChanged();
			}
		}
	}
	
	[Column(Storage="_pvcid", DbType="VarChar(50)")]
	public string pvcid
	{
		get
		{
			return this._pvcid;
		}
		set
		{
			if ((this._pvcid != value))
			{
				this.OnpvcidChanging(value);
				this.SendPropertyChanging();
				this._pvcid = value;
				this.SendPropertyChanged("pvcid");
				this.OnpvcidChanged();
			}
		}
	}
	
	[Column(Storage="_bdjfvlan", DbType="VarChar(200)")]
	public string bdjfvlan
	{
		get
		{
			return this._bdjfvlan;
		}
		set
		{
			if ((this._bdjfvlan != value))
			{
				this.OnbdjfvlanChanging(value);
				this.SendPropertyChanging();
				this._bdjfvlan = value;
				this.SendPropertyChanged("bdjfvlan");
				this.OnbdjfvlanChanged();
			}
		}
	}
	
	[Column(Storage="_ddjfvlan", DbType="VarChar(200)")]
	public string ddjfvlan
	{
		get
		{
			return this._ddjfvlan;
		}
		set
		{
			if ((this._ddjfvlan != value))
			{
				this.OnddjfvlanChanging(value);
				this.SendPropertyChanging();
				this._ddjfvlan = value;
				this.SendPropertyChanged("ddjfvlan");
				this.OnddjfvlanChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbbh", DbType="VarChar(50)")]
	public string ddsbbh
	{
		get
		{
			return this._ddsbbh;
		}
		set
		{
			if ((this._ddsbbh != value))
			{
				this.OnddsbbhChanging(value);
				this.SendPropertyChanging();
				this._ddsbbh = value;
				this.SendPropertyChanged("ddsbbh");
				this.OnddsbbhChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbmc", DbType="NVarChar(50)")]
	public string ddsbmc
	{
		get
		{
			return this._ddsbmc;
		}
		set
		{
			if ((this._ddsbmc != value))
			{
				this.OnddsbmcChanging(value);
				this.SendPropertyChanging();
				this._ddsbmc = value;
				this.SendPropertyChanged("ddsbmc");
				this.OnddsbmcChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbdk", DbType="VarChar(50)")]
	public string ddsbdk
	{
		get
		{
			return this._ddsbdk;
		}
		set
		{
			if ((this._ddsbdk != value))
			{
				this.OnddsbdkChanging(value);
				this.SendPropertyChanging();
				this._ddsbdk = value;
				this.SendPropertyChanged("ddsbdk");
				this.OnddsbdkChanged();
			}
		}
	}
	
	[Column(Storage="_macid", DbType="VarChar(20)")]
	public string macid
	{
		get
		{
			return this._macid;
		}
		set
		{
			if ((this._macid != value))
			{
				this.OnmacidChanging(value);
				this.SendPropertyChanging();
				this._macid = value;
				this.SendPropertyChanged("macid");
				this.OnmacidChanged();
			}
		}
	}
	
	[Column(Storage="_dd_macid", DbType="VarChar(20)")]
	public string dd_macid
	{
		get
		{
			return this._dd_macid;
		}
		set
		{
			if ((this._dd_macid != value))
			{
				this.Ondd_macidChanging(value);
				this.SendPropertyChanging();
				this._dd_macid = value;
				this.SendPropertyChanged("dd_macid");
				this.Ondd_macidChanged();
			}
		}
	}
	
	[Column(Storage="_sbpzxx", DbType="NVarChar(200)")]
	public string sbpzxx
	{
		get
		{
			return this._sbpzxx;
		}
		set
		{
			if ((this._sbpzxx != value))
			{
				this.OnsbpzxxChanging(value);
				this.SendPropertyChanging();
				this._sbpzxx = value;
				this.SendPropertyChanged("sbpzxx");
				this.OnsbpzxxChanged();
			}
		}
	}
	
	[Column(Storage="_Sbdkhid", DbType="NVarChar(20)")]
	public string Sbdkhid
	{
		get
		{
			return this._Sbdkhid;
		}
		set
		{
			if ((this._Sbdkhid != value))
			{
				this.OnSbdkhidChanging(value);
				this.SendPropertyChanging();
				this._Sbdkhid = value;
				this.SendPropertyChanged("Sbdkhid");
				this.OnSbdkhidChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbdkhid", DbType="NVarChar(20)")]
	public string ddsbdkhid
	{
		get
		{
			return this._ddsbdkhid;
		}
		set
		{
			if ((this._ddsbdkhid != value))
			{
				this.OnddsbdkhidChanging(value);
				this.SendPropertyChanging();
				this._ddsbdkhid = value;
				this.SendPropertyChanged("ddsbdkhid");
				this.OnddsbdkhidChanged();
			}
		}
	}
	
	[Column(Storage="_gjsj", DbType="VarChar(10)")]
	public string gjsj
	{
		get
		{
			return this._gjsj;
		}
		set
		{
			if ((this._gjsj != value))
			{
				this.OngjsjChanging(value);
				this.SendPropertyChanging();
				this._gjsj = value;
				this.SendPropertyChanged("gjsj");
				this.OngjsjChanged();
			}
		}
	}
	
	[Column(Storage="_gjremark", DbType="NVarChar(4000)")]
	public string gjremark
	{
		get
		{
			return this._gjremark;
		}
		set
		{
			if ((this._gjremark != value))
			{
				this.OngjremarkChanging(value);
				this.SendPropertyChanging();
				this._gjremark = value;
				this.SendPropertyChanged("gjremark");
				this.OngjremarkChanged();
			}
		}
	}
	
	[Column(Storage="_LjjfID", DbType="VarChar(50)")]
	public string LjjfID
	{
		get
		{
			return this._LjjfID;
		}
		set
		{
			if ((this._LjjfID != value))
			{
				this.OnLjjfIDChanging(value);
				this.SendPropertyChanging();
				this._LjjfID = value;
				this.SendPropertyChanged("LjjfID");
				this.OnLjjfIDChanged();
			}
		}
	}
	
	[Column(Storage="_DdLjjfID", DbType="VarChar(50)")]
	public string DdLjjfID
	{
		get
		{
			return this._DdLjjfID;
		}
		set
		{
			if ((this._DdLjjfID != value))
			{
				this.OnDdLjjfIDChanging(value);
				this.SendPropertyChanging();
				this._DdLjjfID = value;
				this.SendPropertyChanged("DdLjjfID");
				this.OnDdLjjfIDChanged();
			}
		}
	}
	
	[Column(Storage="_Ssqy", DbType="NVarChar(50)")]
	public string Ssqy
	{
		get
		{
			return this._Ssqy;
		}
		set
		{
			if ((this._Ssqy != value))
			{
				this.OnSsqyChanging(value);
				this.SendPropertyChanging();
				this._Ssqy = value;
				this.SendPropertyChanged("Ssqy");
				this.OnSsqyChanged();
			}
		}
	}
	
	[Column(Storage="_Csts", DbType="BigInt")]
	public System.Nullable<long> Csts
	{
		get
		{
			return this._Csts;
		}
		set
		{
			if ((this._Csts != value))
			{
				this.OnCstsChanging(value);
				this.SendPropertyChanging();
				this._Csts = value;
				this.SendPropertyChanged("Csts");
				this.OnCstsChanged();
			}
		}
	}
	
	[Column(Storage="_Cjr", DbType="NVarChar(50)")]
	public string Cjr
	{
		get
		{
			return this._Cjr;
		}
		set
		{
			if ((this._Cjr != value))
			{
				this.OnCjrChanging(value);
				this.SendPropertyChanging();
				this._Cjr = value;
				this.SendPropertyChanged("Cjr");
				this.OnCjrChanged();
			}
		}
	}
	
	[Column(Storage="_Cjrq", DbType="VarChar(25)")]
	public string Cjrq
	{
		get
		{
			return this._Cjrq;
		}
		set
		{
			if ((this._Cjrq != value))
			{
				this.OnCjrqChanging(value);
				this.SendPropertyChanging();
				this._Cjrq = value;
				this.SendPropertyChanged("Cjrq");
				this.OnCjrqChanged();
			}
		}
	}
	
	[Column(Storage="_Cssj", DbType="VarChar(25)")]
	public string Cssj
	{
		get
		{
			return this._Cssj;
		}
		set
		{
			if ((this._Cssj != value))
			{
				this.OnCssjChanging(value);
				this.SendPropertyChanging();
				this._Cssj = value;
				this.SendPropertyChanged("Cssj");
				this.OnCssjChanged();
			}
		}
	}
	
	[Column(Storage="_issend", DbType="VarChar(25)")]
	public string issend
	{
		get
		{
			return this._issend;
		}
		set
		{
			if ((this._issend != value))
			{
				this.OnissendChanging(value);
				this.SendPropertyChanging();
				this._issend = value;
				this.SendPropertyChanged("issend");
				this.OnissendChanged();
			}
		}
	}
	
	[Column(Storage="_OUNdk_Dd", DbType="NVarChar(1000)")]
	public string OUNdk_Dd
	{
		get
		{
			return this._OUNdk_Dd;
		}
		set
		{
			if ((this._OUNdk_Dd != value))
			{
				this.OnOUNdk_DdChanging(value);
				this.SendPropertyChanging();
				this._OUNdk_Dd = value;
				this.SendPropertyChanged("OUNdk_Dd");
				this.OnOUNdk_DdChanged();
			}
		}
	}
	
	[Column(Storage="_glYwONULsh", DbType="NVarChar(50)")]
	public string glYwONULsh
	{
		get
		{
			return this._glYwONULsh;
		}
		set
		{
			if ((this._glYwONULsh != value))
			{
				this.OnglYwONULshChanging(value);
				this.SendPropertyChanging();
				this._glYwONULsh = value;
				this.SendPropertyChanged("glYwONULsh");
				this.OnglYwONULshChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.TS_ZD_Info")]
public partial class TS_ZD_Info
{
	
	private string _type;
	
	private string _lsh;
	
	private string _mc;
	
	private string _code;
	
	private string _bz;
	
	private string _czj;
	
	private string _czrq;
	
	private System.Nullable<bool> _tag;
	
	private string _flag;
	
	private string _YwlbLsh;
	
	private System.Nullable<int> _Sfxs;
	
	private string _Color;
	
	private System.Nullable<long> _xh;
	
	public TS_ZD_Info()
	{
	}
	
	[Column(Storage="_type", DbType="VarChar(50)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this._type = value;
			}
		}
	}
	
	[Column(Storage="_lsh", DbType="VarChar(20)")]
	public string lsh
	{
		get
		{
			return this._lsh;
		}
		set
		{
			if ((this._lsh != value))
			{
				this._lsh = value;
			}
		}
	}
	
	[Column(Storage="_mc", DbType="VarChar(100)")]
	public string mc
	{
		get
		{
			return this._mc;
		}
		set
		{
			if ((this._mc != value))
			{
				this._mc = value;
			}
		}
	}
	
	[Column(Storage="_code", DbType="VarChar(100)")]
	public string code
	{
		get
		{
			return this._code;
		}
		set
		{
			if ((this._code != value))
			{
				this._code = value;
			}
		}
	}
	
	[Column(Storage="_bz", DbType="VarChar(100)")]
	public string bz
	{
		get
		{
			return this._bz;
		}
		set
		{
			if ((this._bz != value))
			{
				this._bz = value;
			}
		}
	}
	
	[Column(Storage="_czj", DbType="VarChar(20)")]
	public string czj
	{
		get
		{
			return this._czj;
		}
		set
		{
			if ((this._czj != value))
			{
				this._czj = value;
			}
		}
	}
	
	[Column(Storage="_czrq", DbType="VarChar(20)")]
	public string czrq
	{
		get
		{
			return this._czrq;
		}
		set
		{
			if ((this._czrq != value))
			{
				this._czrq = value;
			}
		}
	}
	
	[Column(Storage="_tag", DbType="Bit")]
	public System.Nullable<bool> tag
	{
		get
		{
			return this._tag;
		}
		set
		{
			if ((this._tag != value))
			{
				this._tag = value;
			}
		}
	}
	
	[Column(Storage="_flag", DbType="VarChar(5)")]
	public string flag
	{
		get
		{
			return this._flag;
		}
		set
		{
			if ((this._flag != value))
			{
				this._flag = value;
			}
		}
	}
	
	[Column(Storage="_YwlbLsh", DbType="NVarChar(50)")]
	public string YwlbLsh
	{
		get
		{
			return this._YwlbLsh;
		}
		set
		{
			if ((this._YwlbLsh != value))
			{
				this._YwlbLsh = value;
			}
		}
	}
	
	[Column(Storage="_Sfxs", DbType="Int")]
	public System.Nullable<int> Sfxs
	{
		get
		{
			return this._Sfxs;
		}
		set
		{
			if ((this._Sfxs != value))
			{
				this._Sfxs = value;
			}
		}
	}
	
	[Column(Storage="_Color", DbType="NVarChar(50)")]
	public string Color
	{
		get
		{
			return this._Color;
		}
		set
		{
			if ((this._Color != value))
			{
				this._Color = value;
			}
		}
	}
	
	[Column(Storage="_xh", DbType="BigInt")]
	public System.Nullable<long> xh
	{
		get
		{
			return this._xh;
		}
		set
		{
			if ((this._xh != value))
			{
				this._xh = value;
			}
		}
	}
}

[Table(Name="dbo.Jrlx_List")]
public partial class Jrlx_List : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _nodeid;
	
	private string _parentid;
	
	private string _nodename;
	
	private string _form;
	
	private System.Nullable<int> _showorder;
	
	private string _bz;
	
	private System.Nullable<int> _bmgzID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnodeidChanging(string value);
    partial void OnnodeidChanged();
    partial void OnparentidChanging(string value);
    partial void OnparentidChanged();
    partial void OnnodenameChanging(string value);
    partial void OnnodenameChanged();
    partial void OnformChanging(string value);
    partial void OnformChanged();
    partial void OnshoworderChanging(System.Nullable<int> value);
    partial void OnshoworderChanged();
    partial void OnbzChanging(string value);
    partial void OnbzChanged();
    partial void OnbmgzIDChanging(System.Nullable<int> value);
    partial void OnbmgzIDChanged();
    #endregion
	
	public Jrlx_List()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_nodeid", DbType="VarChar(20)")]
	public string nodeid
	{
		get
		{
			return this._nodeid;
		}
		set
		{
			if ((this._nodeid != value))
			{
				this.OnnodeidChanging(value);
				this.SendPropertyChanging();
				this._nodeid = value;
				this.SendPropertyChanged("nodeid");
				this.OnnodeidChanged();
			}
		}
	}
	
	[Column(Storage="_parentid", DbType="VarChar(20)")]
	public string parentid
	{
		get
		{
			return this._parentid;
		}
		set
		{
			if ((this._parentid != value))
			{
				this.OnparentidChanging(value);
				this.SendPropertyChanging();
				this._parentid = value;
				this.SendPropertyChanged("parentid");
				this.OnparentidChanged();
			}
		}
	}
	
	[Column(Storage="_nodename", DbType="NVarChar(50)")]
	public string nodename
	{
		get
		{
			return this._nodename;
		}
		set
		{
			if ((this._nodename != value))
			{
				this.OnnodenameChanging(value);
				this.SendPropertyChanging();
				this._nodename = value;
				this.SendPropertyChanged("nodename");
				this.OnnodenameChanged();
			}
		}
	}
	
	[Column(Storage="_form", DbType="NVarChar(100)")]
	public string form
	{
		get
		{
			return this._form;
		}
		set
		{
			if ((this._form != value))
			{
				this.OnformChanging(value);
				this.SendPropertyChanging();
				this._form = value;
				this.SendPropertyChanged("form");
				this.OnformChanged();
			}
		}
	}
	
	[Column(Storage="_showorder", DbType="Int")]
	public System.Nullable<int> showorder
	{
		get
		{
			return this._showorder;
		}
		set
		{
			if ((this._showorder != value))
			{
				this.OnshoworderChanging(value);
				this.SendPropertyChanging();
				this._showorder = value;
				this.SendPropertyChanged("showorder");
				this.OnshoworderChanged();
			}
		}
	}
	
	[Column(Storage="_bz", DbType="NVarChar(100)")]
	public string bz
	{
		get
		{
			return this._bz;
		}
		set
		{
			if ((this._bz != value))
			{
				this.OnbzChanging(value);
				this.SendPropertyChanging();
				this._bz = value;
				this.SendPropertyChanged("bz");
				this.OnbzChanged();
			}
		}
	}
	
	[Column(Storage="_bmgzID", DbType="Int")]
	public System.Nullable<int> bmgzID
	{
		get
		{
			return this._bmgzID;
		}
		set
		{
			if ((this._bmgzID != value))
			{
				this.OnbmgzIDChanging(value);
				this.SendPropertyChanging();
				this._bmgzID = value;
				this.SendPropertyChanged("bmgzID");
				this.OnbmgzIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.AssemblyPortSource_Master")]
public partial class AssemblyPortSource_Master
{
	
	private int _ID;
	
	private string _sbbh;
	
	private string _sbmc;
	
	private string _sbxh;
	
	private string _zcbh;
	
	private string _mac_id;
	
	private string _mac_name;
	
	private string _sccj;
	
	private string _sbdj;
	
	private string _sbfl;
	
	private string _sbzt;
	
	private string _xlh;
	
	private string _nzxx;
	
	private System.Nullable<int> _dymks;
	
	private string _rjxx;
	
	private string _yzcw;
	
	private string _kycw;
	
	private string _sfxb;
	
	private string _bxqsrq;
	
	private string _bxjzrq;
	
	private string _RMAjl;
	
	private string _xmbh;
	
	private string _cghth;
	
	private string _cgf;
	
	private string _bz;
	
	private string _zddks;
	
	private string _sbgldz;
	
	private string _sljfbh;
	
	private string _sljfmc;
	
	private string _bk;
	
	private string _macdzonu;
	
	private string _gsjbh;
	
	private string _jfxh;
	
	private string _gjsj;
	
	private string _gjremark;
	
	private string _Ssqy;
	
	public AssemblyPortSource_Master()
	{
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[Column(Storage="_sbbh", DbType="VarChar(30)")]
	public string sbbh
	{
		get
		{
			return this._sbbh;
		}
		set
		{
			if ((this._sbbh != value))
			{
				this._sbbh = value;
			}
		}
	}
	
	[Column(Storage="_sbmc", DbType="NVarChar(50)")]
	public string sbmc
	{
		get
		{
			return this._sbmc;
		}
		set
		{
			if ((this._sbmc != value))
			{
				this._sbmc = value;
			}
		}
	}
	
	[Column(Storage="_sbxh", DbType="VarChar(30)")]
	public string sbxh
	{
		get
		{
			return this._sbxh;
		}
		set
		{
			if ((this._sbxh != value))
			{
				this._sbxh = value;
			}
		}
	}
	
	[Column(Storage="_zcbh", DbType="VarChar(15)")]
	public string zcbh
	{
		get
		{
			return this._zcbh;
		}
		set
		{
			if ((this._zcbh != value))
			{
				this._zcbh = value;
			}
		}
	}
	
	[Column(Storage="_mac_id", DbType="VarChar(30)")]
	public string mac_id
	{
		get
		{
			return this._mac_id;
		}
		set
		{
			if ((this._mac_id != value))
			{
				this._mac_id = value;
			}
		}
	}
	
	[Column(Storage="_mac_name", DbType="VarChar(1000)")]
	public string mac_name
	{
		get
		{
			return this._mac_name;
		}
		set
		{
			if ((this._mac_name != value))
			{
				this._mac_name = value;
			}
		}
	}
	
	[Column(Storage="_sccj", DbType="NVarChar(200)")]
	public string sccj
	{
		get
		{
			return this._sccj;
		}
		set
		{
			if ((this._sccj != value))
			{
				this._sccj = value;
			}
		}
	}
	
	[Column(Storage="_sbdj", DbType="VarChar(50)")]
	public string sbdj
	{
		get
		{
			return this._sbdj;
		}
		set
		{
			if ((this._sbdj != value))
			{
				this._sbdj = value;
			}
		}
	}
	
	[Column(Storage="_sbfl", DbType="VarChar(20)")]
	public string sbfl
	{
		get
		{
			return this._sbfl;
		}
		set
		{
			if ((this._sbfl != value))
			{
				this._sbfl = value;
			}
		}
	}
	
	[Column(Storage="_sbzt", DbType="VarChar(20)")]
	public string sbzt
	{
		get
		{
			return this._sbzt;
		}
		set
		{
			if ((this._sbzt != value))
			{
				this._sbzt = value;
			}
		}
	}
	
	[Column(Storage="_xlh", DbType="VarChar(20)")]
	public string xlh
	{
		get
		{
			return this._xlh;
		}
		set
		{
			if ((this._xlh != value))
			{
				this._xlh = value;
			}
		}
	}
	
	[Column(Storage="_nzxx", DbType="VarChar(50)")]
	public string nzxx
	{
		get
		{
			return this._nzxx;
		}
		set
		{
			if ((this._nzxx != value))
			{
				this._nzxx = value;
			}
		}
	}
	
	[Column(Storage="_dymks", DbType="Int")]
	public System.Nullable<int> dymks
	{
		get
		{
			return this._dymks;
		}
		set
		{
			if ((this._dymks != value))
			{
				this._dymks = value;
			}
		}
	}
	
	[Column(Storage="_rjxx", DbType="VarChar(100)")]
	public string rjxx
	{
		get
		{
			return this._rjxx;
		}
		set
		{
			if ((this._rjxx != value))
			{
				this._rjxx = value;
			}
		}
	}
	
	[Column(Storage="_yzcw", DbType="VarChar(20)")]
	public string yzcw
	{
		get
		{
			return this._yzcw;
		}
		set
		{
			if ((this._yzcw != value))
			{
				this._yzcw = value;
			}
		}
	}
	
	[Column(Storage="_kycw", DbType="VarChar(20)")]
	public string kycw
	{
		get
		{
			return this._kycw;
		}
		set
		{
			if ((this._kycw != value))
			{
				this._kycw = value;
			}
		}
	}
	
	[Column(Storage="_sfxb", DbType="VarChar(20)")]
	public string sfxb
	{
		get
		{
			return this._sfxb;
		}
		set
		{
			if ((this._sfxb != value))
			{
				this._sfxb = value;
			}
		}
	}
	
	[Column(Storage="_bxqsrq", DbType="VarChar(20)")]
	public string bxqsrq
	{
		get
		{
			return this._bxqsrq;
		}
		set
		{
			if ((this._bxqsrq != value))
			{
				this._bxqsrq = value;
			}
		}
	}
	
	[Column(Storage="_bxjzrq", DbType="VarChar(20)")]
	public string bxjzrq
	{
		get
		{
			return this._bxjzrq;
		}
		set
		{
			if ((this._bxjzrq != value))
			{
				this._bxjzrq = value;
			}
		}
	}
	
	[Column(Storage="_RMAjl", DbType="VarChar(100)")]
	public string RMAjl
	{
		get
		{
			return this._RMAjl;
		}
		set
		{
			if ((this._RMAjl != value))
			{
				this._RMAjl = value;
			}
		}
	}
	
	[Column(Storage="_xmbh", DbType="VarChar(20)")]
	public string xmbh
	{
		get
		{
			return this._xmbh;
		}
		set
		{
			if ((this._xmbh != value))
			{
				this._xmbh = value;
			}
		}
	}
	
	[Column(Storage="_cghth", DbType="VarChar(20)")]
	public string cghth
	{
		get
		{
			return this._cghth;
		}
		set
		{
			if ((this._cghth != value))
			{
				this._cghth = value;
			}
		}
	}
	
	[Column(Storage="_cgf", DbType="VarChar(50)")]
	public string cgf
	{
		get
		{
			return this._cgf;
		}
		set
		{
			if ((this._cgf != value))
			{
				this._cgf = value;
			}
		}
	}
	
	[Column(Storage="_bz", DbType="VarChar(8000)")]
	public string bz
	{
		get
		{
			return this._bz;
		}
		set
		{
			if ((this._bz != value))
			{
				this._bz = value;
			}
		}
	}
	
	[Column(Storage="_zddks", DbType="VarChar(50)")]
	public string zddks
	{
		get
		{
			return this._zddks;
		}
		set
		{
			if ((this._zddks != value))
			{
				this._zddks = value;
			}
		}
	}
	
	[Column(Storage="_sbgldz", DbType="VarChar(50)")]
	public string sbgldz
	{
		get
		{
			return this._sbgldz;
		}
		set
		{
			if ((this._sbgldz != value))
			{
				this._sbgldz = value;
			}
		}
	}
	
	[Column(Storage="_sljfbh", DbType="VarChar(50)")]
	public string sljfbh
	{
		get
		{
			return this._sljfbh;
		}
		set
		{
			if ((this._sljfbh != value))
			{
				this._sljfbh = value;
			}
		}
	}
	
	[Column(Storage="_sljfmc", DbType="VarChar(50)")]
	public string sljfmc
	{
		get
		{
			return this._sljfmc;
		}
		set
		{
			if ((this._sljfmc != value))
			{
				this._sljfmc = value;
			}
		}
	}
	
	[Column(Storage="_bk", DbType="VarChar(50)")]
	public string bk
	{
		get
		{
			return this._bk;
		}
		set
		{
			if ((this._bk != value))
			{
				this._bk = value;
			}
		}
	}
	
	[Column(Storage="_macdzonu", DbType="VarChar(100)")]
	public string macdzonu
	{
		get
		{
			return this._macdzonu;
		}
		set
		{
			if ((this._macdzonu != value))
			{
				this._macdzonu = value;
			}
		}
	}
	
	[Column(Storage="_gsjbh", DbType="VarChar(100)")]
	public string gsjbh
	{
		get
		{
			return this._gsjbh;
		}
		set
		{
			if ((this._gsjbh != value))
			{
				this._gsjbh = value;
			}
		}
	}
	
	[Column(Storage="_jfxh", DbType="VarChar(50)")]
	public string jfxh
	{
		get
		{
			return this._jfxh;
		}
		set
		{
			if ((this._jfxh != value))
			{
				this._jfxh = value;
			}
		}
	}
	
	[Column(Storage="_gjsj", DbType="VarChar(10)")]
	public string gjsj
	{
		get
		{
			return this._gjsj;
		}
		set
		{
			if ((this._gjsj != value))
			{
				this._gjsj = value;
			}
		}
	}
	
	[Column(Storage="_gjremark", DbType="NVarChar(4000)")]
	public string gjremark
	{
		get
		{
			return this._gjremark;
		}
		set
		{
			if ((this._gjremark != value))
			{
				this._gjremark = value;
			}
		}
	}
	
	[Column(Storage="_Ssqy", DbType="NVarChar(50)")]
	public string Ssqy
	{
		get
		{
			return this._Ssqy;
		}
		set
		{
			if ((this._Ssqy != value))
			{
				this._Ssqy = value;
			}
		}
	}
}

[Table(Name="dbo.AssemblyPortSource_Details")]
public partial class AssemblyPortSource_Details : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _MID;
	
	private string _port;
	
	private string _sssbbh;
	
	private string _dksl;
	
	private string _dkll;
	
	private string _dkzt;
	
	private string _sfky;
	
	private string _Cw;
	
	private string _Ccjb;
	
	private string _bklx;
	
	private System.Nullable<long> _xh;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMIDChanging(System.Nullable<int> value);
    partial void OnMIDChanged();
    partial void OnportChanging(string value);
    partial void OnportChanged();
    partial void OnsssbbhChanging(string value);
    partial void OnsssbbhChanged();
    partial void OndkslChanging(string value);
    partial void OndkslChanged();
    partial void OndkllChanging(string value);
    partial void OndkllChanged();
    partial void OndkztChanging(string value);
    partial void OndkztChanged();
    partial void OnsfkyChanging(string value);
    partial void OnsfkyChanged();
    partial void OnCwChanging(string value);
    partial void OnCwChanged();
    partial void OnCcjbChanging(string value);
    partial void OnCcjbChanged();
    partial void OnbklxChanging(string value);
    partial void OnbklxChanged();
    partial void OnxhChanging(System.Nullable<long> value);
    partial void OnxhChanged();
    #endregion
	
	public AssemblyPortSource_Details()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_MID", DbType="Int")]
	public System.Nullable<int> MID
	{
		get
		{
			return this._MID;
		}
		set
		{
			if ((this._MID != value))
			{
				this.OnMIDChanging(value);
				this.SendPropertyChanging();
				this._MID = value;
				this.SendPropertyChanged("MID");
				this.OnMIDChanged();
			}
		}
	}
	
	[Column(Storage="_port", DbType="VarChar(20)")]
	public string port
	{
		get
		{
			return this._port;
		}
		set
		{
			if ((this._port != value))
			{
				this.OnportChanging(value);
				this.SendPropertyChanging();
				this._port = value;
				this.SendPropertyChanged("port");
				this.OnportChanged();
			}
		}
	}
	
	[Column(Storage="_sssbbh", DbType="NVarChar(50)")]
	public string sssbbh
	{
		get
		{
			return this._sssbbh;
		}
		set
		{
			if ((this._sssbbh != value))
			{
				this.OnsssbbhChanging(value);
				this.SendPropertyChanging();
				this._sssbbh = value;
				this.SendPropertyChanged("sssbbh");
				this.OnsssbbhChanged();
			}
		}
	}
	
	[Column(Storage="_dksl", DbType="VarChar(30)")]
	public string dksl
	{
		get
		{
			return this._dksl;
		}
		set
		{
			if ((this._dksl != value))
			{
				this.OndkslChanging(value);
				this.SendPropertyChanging();
				this._dksl = value;
				this.SendPropertyChanged("dksl");
				this.OndkslChanged();
			}
		}
	}
	
	[Column(Storage="_dkll", DbType="NVarChar(50)")]
	public string dkll
	{
		get
		{
			return this._dkll;
		}
		set
		{
			if ((this._dkll != value))
			{
				this.OndkllChanging(value);
				this.SendPropertyChanging();
				this._dkll = value;
				this.SendPropertyChanged("dkll");
				this.OndkllChanged();
			}
		}
	}
	
	[Column(Storage="_dkzt", DbType="VarChar(30)")]
	public string dkzt
	{
		get
		{
			return this._dkzt;
		}
		set
		{
			if ((this._dkzt != value))
			{
				this.OndkztChanging(value);
				this.SendPropertyChanging();
				this._dkzt = value;
				this.SendPropertyChanged("dkzt");
				this.OndkztChanged();
			}
		}
	}
	
	[Column(Storage="_sfky", DbType="VarChar(50)")]
	public string sfky
	{
		get
		{
			return this._sfky;
		}
		set
		{
			if ((this._sfky != value))
			{
				this.OnsfkyChanging(value);
				this.SendPropertyChanging();
				this._sfky = value;
				this.SendPropertyChanged("sfky");
				this.OnsfkyChanged();
			}
		}
	}
	
	[Column(Storage="_Cw", DbType="NVarChar(50)")]
	public string Cw
	{
		get
		{
			return this._Cw;
		}
		set
		{
			if ((this._Cw != value))
			{
				this.OnCwChanging(value);
				this.SendPropertyChanging();
				this._Cw = value;
				this.SendPropertyChanged("Cw");
				this.OnCwChanged();
			}
		}
	}
	
	[Column(Storage="_Ccjb", DbType="NVarChar(25)")]
	public string Ccjb
	{
		get
		{
			return this._Ccjb;
		}
		set
		{
			if ((this._Ccjb != value))
			{
				this.OnCcjbChanging(value);
				this.SendPropertyChanging();
				this._Ccjb = value;
				this.SendPropertyChanged("Ccjb");
				this.OnCcjbChanged();
			}
		}
	}
	
	[Column(Storage="_bklx", DbType="NVarChar(25)")]
	public string bklx
	{
		get
		{
			return this._bklx;
		}
		set
		{
			if ((this._bklx != value))
			{
				this.OnbklxChanging(value);
				this.SendPropertyChanging();
				this._bklx = value;
				this.SendPropertyChanged("bklx");
				this.OnbklxChanged();
			}
		}
	}
	
	[Column(Storage="_xh", DbType="BigInt")]
	public System.Nullable<long> xh
	{
		get
		{
			return this._xh;
		}
		set
		{
			if ((this._xh != value))
			{
				this.OnxhChanging(value);
				this.SendPropertyChanging();
				this._xh = value;
				this.SendPropertyChanged("xh");
				this.OnxhChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.ONU_Dk")]
public partial class ONU_Dk : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _ID;
	
	private string _Lsh;
	
	private System.Nullable<int> _Gldkid;
	
	private System.Nullable<int> _MID;
	
	private string _Dkh;
	
	private string _Dklx;
	
	private string _Dksl;
	
	private System.Nullable<int> _Sfkfy;
	
	private System.Nullable<int> _Dkzt;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnLshChanging(string value);
    partial void OnLshChanged();
    partial void OnGldkidChanging(System.Nullable<int> value);
    partial void OnGldkidChanged();
    partial void OnMIDChanging(System.Nullable<int> value);
    partial void OnMIDChanged();
    partial void OnDkhChanging(string value);
    partial void OnDkhChanged();
    partial void OnDklxChanging(string value);
    partial void OnDklxChanged();
    partial void OnDkslChanging(string value);
    partial void OnDkslChanged();
    partial void OnSfkfyChanging(System.Nullable<int> value);
    partial void OnSfkfyChanged();
    partial void OnDkztChanging(System.Nullable<int> value);
    partial void OnDkztChanged();
    #endregion
	
	public ONU_Dk()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_Lsh", DbType="NVarChar(50)")]
	public string Lsh
	{
		get
		{
			return this._Lsh;
		}
		set
		{
			if ((this._Lsh != value))
			{
				this.OnLshChanging(value);
				this.SendPropertyChanging();
				this._Lsh = value;
				this.SendPropertyChanged("Lsh");
				this.OnLshChanged();
			}
		}
	}
	
	[Column(Storage="_Gldkid", DbType="Int")]
	public System.Nullable<int> Gldkid
	{
		get
		{
			return this._Gldkid;
		}
		set
		{
			if ((this._Gldkid != value))
			{
				this.OnGldkidChanging(value);
				this.SendPropertyChanging();
				this._Gldkid = value;
				this.SendPropertyChanged("Gldkid");
				this.OnGldkidChanged();
			}
		}
	}
	
	[Column(Storage="_MID", DbType="Int")]
	public System.Nullable<int> MID
	{
		get
		{
			return this._MID;
		}
		set
		{
			if ((this._MID != value))
			{
				this.OnMIDChanging(value);
				this.SendPropertyChanging();
				this._MID = value;
				this.SendPropertyChanged("MID");
				this.OnMIDChanged();
			}
		}
	}
	
	[Column(Storage="_Dkh", DbType="NVarChar(25)")]
	public string Dkh
	{
		get
		{
			return this._Dkh;
		}
		set
		{
			if ((this._Dkh != value))
			{
				this.OnDkhChanging(value);
				this.SendPropertyChanging();
				this._Dkh = value;
				this.SendPropertyChanged("Dkh");
				this.OnDkhChanged();
			}
		}
	}
	
	[Column(Storage="_Dklx", DbType="NVarChar(25)")]
	public string Dklx
	{
		get
		{
			return this._Dklx;
		}
		set
		{
			if ((this._Dklx != value))
			{
				this.OnDklxChanging(value);
				this.SendPropertyChanging();
				this._Dklx = value;
				this.SendPropertyChanged("Dklx");
				this.OnDklxChanged();
			}
		}
	}
	
	[Column(Storage="_Dksl", DbType="NVarChar(25)")]
	public string Dksl
	{
		get
		{
			return this._Dksl;
		}
		set
		{
			if ((this._Dksl != value))
			{
				this.OnDkslChanging(value);
				this.SendPropertyChanging();
				this._Dksl = value;
				this.SendPropertyChanged("Dksl");
				this.OnDkslChanged();
			}
		}
	}
	
	[Column(Storage="_Sfkfy", DbType="Int")]
	public System.Nullable<int> Sfkfy
	{
		get
		{
			return this._Sfkfy;
		}
		set
		{
			if ((this._Sfkfy != value))
			{
				this.OnSfkfyChanging(value);
				this.SendPropertyChanging();
				this._Sfkfy = value;
				this.SendPropertyChanged("Sfkfy");
				this.OnSfkfyChanged();
			}
		}
	}
	
	[Column(Storage="_Dkzt", DbType="Int")]
	public System.Nullable<int> Dkzt
	{
		get
		{
			return this._Dkzt;
		}
		set
		{
			if ((this._Dkzt != value))
			{
				this.OnDkztChanging(value);
				this.SendPropertyChanging();
				this._Dkzt = value;
				this.SendPropertyChanged("Dkzt");
				this.OnDkztChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.YwONU_glb")]
public partial class YwONU_glb : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _ID;
	
	private string _Lsh;
	
	private System.Nullable<long> _Ywid;
	
	private string _ONULsh;
	
	private System.Nullable<long> _type;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnLshChanging(string value);
    partial void OnLshChanged();
    partial void OnYwidChanging(System.Nullable<long> value);
    partial void OnYwidChanged();
    partial void OnONULshChanging(string value);
    partial void OnONULshChanged();
    partial void OntypeChanging(System.Nullable<long> value);
    partial void OntypeChanged();
    #endregion
	
	public YwONU_glb()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_Lsh", DbType="NVarChar(50)")]
	public string Lsh
	{
		get
		{
			return this._Lsh;
		}
		set
		{
			if ((this._Lsh != value))
			{
				this.OnLshChanging(value);
				this.SendPropertyChanging();
				this._Lsh = value;
				this.SendPropertyChanged("Lsh");
				this.OnLshChanged();
			}
		}
	}
	
	[Column(Storage="_Ywid", DbType="BigInt")]
	public System.Nullable<long> Ywid
	{
		get
		{
			return this._Ywid;
		}
		set
		{
			if ((this._Ywid != value))
			{
				this.OnYwidChanging(value);
				this.SendPropertyChanging();
				this._Ywid = value;
				this.SendPropertyChanged("Ywid");
				this.OnYwidChanged();
			}
		}
	}
	
	[Column(Storage="_ONULsh", DbType="VarChar(50)")]
	public string ONULsh
	{
		get
		{
			return this._ONULsh;
		}
		set
		{
			if ((this._ONULsh != value))
			{
				this.OnONULshChanging(value);
				this.SendPropertyChanging();
				this._ONULsh = value;
				this.SendPropertyChanged("ONULsh");
				this.OnONULshChanged();
			}
		}
	}
	
	[Column(Storage="_type", DbType="BigInt")]
	public System.Nullable<long> type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.Vlan_Distribute")]
public partial class Vlan_Distribute : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _ID;
	
	private string _VlanID;
	
	private System.Nullable<long> _Ywid;
	
	private string _RelField;
	
	private string _jfID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnVlanIDChanging(string value);
    partial void OnVlanIDChanged();
    partial void OnYwidChanging(System.Nullable<long> value);
    partial void OnYwidChanged();
    partial void OnRelFieldChanging(string value);
    partial void OnRelFieldChanged();
    partial void OnjfIDChanging(string value);
    partial void OnjfIDChanged();
    #endregion
	
	public Vlan_Distribute()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_VlanID", DbType="NVarChar(50)")]
	public string VlanID
	{
		get
		{
			return this._VlanID;
		}
		set
		{
			if ((this._VlanID != value))
			{
				this.OnVlanIDChanging(value);
				this.SendPropertyChanging();
				this._VlanID = value;
				this.SendPropertyChanged("VlanID");
				this.OnVlanIDChanged();
			}
		}
	}
	
	[Column(Storage="_Ywid", DbType="BigInt")]
	public System.Nullable<long> Ywid
	{
		get
		{
			return this._Ywid;
		}
		set
		{
			if ((this._Ywid != value))
			{
				this.OnYwidChanging(value);
				this.SendPropertyChanging();
				this._Ywid = value;
				this.SendPropertyChanged("Ywid");
				this.OnYwidChanged();
			}
		}
	}
	
	[Column(Storage="_RelField", DbType="VarChar(20)")]
	public string RelField
	{
		get
		{
			return this._RelField;
		}
		set
		{
			if ((this._RelField != value))
			{
				this.OnRelFieldChanging(value);
				this.SendPropertyChanging();
				this._RelField = value;
				this.SendPropertyChanged("RelField");
				this.OnRelFieldChanged();
			}
		}
	}
	
	[Column(Storage="_jfID", DbType="NVarChar(50)")]
	public string jfID
	{
		get
		{
			return this._jfID;
		}
		set
		{
			if ((this._jfID != value))
			{
				this.OnjfIDChanging(value);
				this.SendPropertyChanging();
				this._jfID = value;
				this.SendPropertyChanged("jfID");
				this.OnjfIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.ts_kh")]
public partial class ts_kh : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _ywbm;
	
	private string _khbh;
	
	private string _khmc;
	
	private string _khdz;
	
	private string _khlx;
	
	private string _czhm;
	
	private string _khlxr;
	
	private string _lxdh;
	
	private string _ydsj;
	
	private string _Email;
	
	private string _jslxr;
	
	private string _jsrdh;
	
	private string _jsrsj;
	
	private string _jsrEmail;
	
	private string _bz;
	
	private string _cjr;
	
	private string _cjrq;
	
	private string _yb;
	
	private string _Zylx;
	
	private string _Khjb;
	
	private string _Xsy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnywbmChanging(string value);
    partial void OnywbmChanged();
    partial void OnkhbhChanging(string value);
    partial void OnkhbhChanged();
    partial void OnkhmcChanging(string value);
    partial void OnkhmcChanged();
    partial void OnkhdzChanging(string value);
    partial void OnkhdzChanged();
    partial void OnkhlxChanging(string value);
    partial void OnkhlxChanged();
    partial void OnczhmChanging(string value);
    partial void OnczhmChanged();
    partial void OnkhlxrChanging(string value);
    partial void OnkhlxrChanged();
    partial void OnlxdhChanging(string value);
    partial void OnlxdhChanged();
    partial void OnydsjChanging(string value);
    partial void OnydsjChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnjslxrChanging(string value);
    partial void OnjslxrChanged();
    partial void OnjsrdhChanging(string value);
    partial void OnjsrdhChanged();
    partial void OnjsrsjChanging(string value);
    partial void OnjsrsjChanged();
    partial void OnjsrEmailChanging(string value);
    partial void OnjsrEmailChanged();
    partial void OnbzChanging(string value);
    partial void OnbzChanged();
    partial void OncjrChanging(string value);
    partial void OncjrChanged();
    partial void OncjrqChanging(string value);
    partial void OncjrqChanged();
    partial void OnybChanging(string value);
    partial void OnybChanged();
    partial void OnZylxChanging(string value);
    partial void OnZylxChanged();
    partial void OnKhjbChanging(string value);
    partial void OnKhjbChanged();
    partial void OnXsyChanging(string value);
    partial void OnXsyChanged();
    #endregion
	
	public ts_kh()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_ywbm", DbType="VarChar(100)")]
	public string ywbm
	{
		get
		{
			return this._ywbm;
		}
		set
		{
			if ((this._ywbm != value))
			{
				this.OnywbmChanging(value);
				this.SendPropertyChanging();
				this._ywbm = value;
				this.SendPropertyChanged("ywbm");
				this.OnywbmChanged();
			}
		}
	}
	
	[Column(Storage="_khbh", DbType="VarChar(15)")]
	public string khbh
	{
		get
		{
			return this._khbh;
		}
		set
		{
			if ((this._khbh != value))
			{
				this.OnkhbhChanging(value);
				this.SendPropertyChanging();
				this._khbh = value;
				this.SendPropertyChanged("khbh");
				this.OnkhbhChanged();
			}
		}
	}
	
	[Column(Storage="_khmc", DbType="NVarChar(100)")]
	public string khmc
	{
		get
		{
			return this._khmc;
		}
		set
		{
			if ((this._khmc != value))
			{
				this.OnkhmcChanging(value);
				this.SendPropertyChanging();
				this._khmc = value;
				this.SendPropertyChanged("khmc");
				this.OnkhmcChanged();
			}
		}
	}
	
	[Column(Storage="_khdz", DbType="NVarChar(200)")]
	public string khdz
	{
		get
		{
			return this._khdz;
		}
		set
		{
			if ((this._khdz != value))
			{
				this.OnkhdzChanging(value);
				this.SendPropertyChanging();
				this._khdz = value;
				this.SendPropertyChanged("khdz");
				this.OnkhdzChanged();
			}
		}
	}
	
	[Column(Storage="_khlx", DbType="NVarChar(30)")]
	public string khlx
	{
		get
		{
			return this._khlx;
		}
		set
		{
			if ((this._khlx != value))
			{
				this.OnkhlxChanging(value);
				this.SendPropertyChanging();
				this._khlx = value;
				this.SendPropertyChanged("khlx");
				this.OnkhlxChanged();
			}
		}
	}
	
	[Column(Storage="_czhm", DbType="VarChar(100)")]
	public string czhm
	{
		get
		{
			return this._czhm;
		}
		set
		{
			if ((this._czhm != value))
			{
				this.OnczhmChanging(value);
				this.SendPropertyChanging();
				this._czhm = value;
				this.SendPropertyChanged("czhm");
				this.OnczhmChanged();
			}
		}
	}
	
	[Column(Storage="_khlxr", DbType="NVarChar(100)")]
	public string khlxr
	{
		get
		{
			return this._khlxr;
		}
		set
		{
			if ((this._khlxr != value))
			{
				this.OnkhlxrChanging(value);
				this.SendPropertyChanging();
				this._khlxr = value;
				this.SendPropertyChanged("khlxr");
				this.OnkhlxrChanged();
			}
		}
	}
	
	[Column(Storage="_lxdh", DbType="VarChar(100)")]
	public string lxdh
	{
		get
		{
			return this._lxdh;
		}
		set
		{
			if ((this._lxdh != value))
			{
				this.OnlxdhChanging(value);
				this.SendPropertyChanging();
				this._lxdh = value;
				this.SendPropertyChanged("lxdh");
				this.OnlxdhChanged();
			}
		}
	}
	
	[Column(Storage="_ydsj", DbType="VarChar(100)")]
	public string ydsj
	{
		get
		{
			return this._ydsj;
		}
		set
		{
			if ((this._ydsj != value))
			{
				this.OnydsjChanging(value);
				this.SendPropertyChanging();
				this._ydsj = value;
				this.SendPropertyChanged("ydsj");
				this.OnydsjChanged();
			}
		}
	}
	
	[Column(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[Column(Storage="_jslxr", DbType="NVarChar(100)")]
	public string jslxr
	{
		get
		{
			return this._jslxr;
		}
		set
		{
			if ((this._jslxr != value))
			{
				this.OnjslxrChanging(value);
				this.SendPropertyChanging();
				this._jslxr = value;
				this.SendPropertyChanged("jslxr");
				this.OnjslxrChanged();
			}
		}
	}
	
	[Column(Storage="_jsrdh", DbType="VarChar(100)")]
	public string jsrdh
	{
		get
		{
			return this._jsrdh;
		}
		set
		{
			if ((this._jsrdh != value))
			{
				this.OnjsrdhChanging(value);
				this.SendPropertyChanging();
				this._jsrdh = value;
				this.SendPropertyChanged("jsrdh");
				this.OnjsrdhChanged();
			}
		}
	}
	
	[Column(Storage="_jsrsj", DbType="VarChar(15)")]
	public string jsrsj
	{
		get
		{
			return this._jsrsj;
		}
		set
		{
			if ((this._jsrsj != value))
			{
				this.OnjsrsjChanging(value);
				this.SendPropertyChanging();
				this._jsrsj = value;
				this.SendPropertyChanged("jsrsj");
				this.OnjsrsjChanged();
			}
		}
	}
	
	[Column(Storage="_jsrEmail", DbType="VarChar(50)")]
	public string jsrEmail
	{
		get
		{
			return this._jsrEmail;
		}
		set
		{
			if ((this._jsrEmail != value))
			{
				this.OnjsrEmailChanging(value);
				this.SendPropertyChanging();
				this._jsrEmail = value;
				this.SendPropertyChanged("jsrEmail");
				this.OnjsrEmailChanged();
			}
		}
	}
	
	[Column(Storage="_bz", DbType="NVarChar(200)")]
	public string bz
	{
		get
		{
			return this._bz;
		}
		set
		{
			if ((this._bz != value))
			{
				this.OnbzChanging(value);
				this.SendPropertyChanging();
				this._bz = value;
				this.SendPropertyChanged("bz");
				this.OnbzChanged();
			}
		}
	}
	
	[Column(Storage="_cjr", DbType="NVarChar(20)")]
	public string cjr
	{
		get
		{
			return this._cjr;
		}
		set
		{
			if ((this._cjr != value))
			{
				this.OncjrChanging(value);
				this.SendPropertyChanging();
				this._cjr = value;
				this.SendPropertyChanged("cjr");
				this.OncjrChanged();
			}
		}
	}
	
	[Column(Storage="_cjrq", DbType="NVarChar(50)")]
	public string cjrq
	{
		get
		{
			return this._cjrq;
		}
		set
		{
			if ((this._cjrq != value))
			{
				this.OncjrqChanging(value);
				this.SendPropertyChanging();
				this._cjrq = value;
				this.SendPropertyChanged("cjrq");
				this.OncjrqChanged();
			}
		}
	}
	
	[Column(Storage="_yb", DbType="NVarChar(50)")]
	public string yb
	{
		get
		{
			return this._yb;
		}
		set
		{
			if ((this._yb != value))
			{
				this.OnybChanging(value);
				this.SendPropertyChanging();
				this._yb = value;
				this.SendPropertyChanged("yb");
				this.OnybChanged();
			}
		}
	}
	
	[Column(Storage="_Zylx", DbType="VarChar(500)")]
	public string Zylx
	{
		get
		{
			return this._Zylx;
		}
		set
		{
			if ((this._Zylx != value))
			{
				this.OnZylxChanging(value);
				this.SendPropertyChanging();
				this._Zylx = value;
				this.SendPropertyChanged("Zylx");
				this.OnZylxChanged();
			}
		}
	}
	
	[Column(Storage="_Khjb", DbType="NVarChar(30)")]
	public string Khjb
	{
		get
		{
			return this._Khjb;
		}
		set
		{
			if ((this._Khjb != value))
			{
				this.OnKhjbChanging(value);
				this.SendPropertyChanging();
				this._Khjb = value;
				this.SendPropertyChanged("Khjb");
				this.OnKhjbChanged();
			}
		}
	}
	
	[Column(Storage="_Xsy", DbType="NVarChar(100)")]
	public string Xsy
	{
		get
		{
			return this._Xsy;
		}
		set
		{
			if ((this._Xsy != value))
			{
				this.OnXsyChanging(value);
				this.SendPropertyChanging();
				this._Xsy = value;
				this.SendPropertyChanged("Xsy");
				this.OnXsyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
