#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="RMSS")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertIP_Bussiness(IP_Bussiness instance);
  partial void UpdateIP_Bussiness(IP_Bussiness instance);
  partial void DeleteIP_Bussiness(IP_Bussiness instance);
  partial void InsertJrlx_List(Jrlx_List instance);
  partial void UpdateJrlx_List(Jrlx_List instance);
  partial void DeleteJrlx_List(Jrlx_List instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RMSSConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<IP_Bussiness> IP_Bussiness
	{
		get
		{
			return this.GetTable<IP_Bussiness>();
		}
	}
	
	public System.Data.Linq.Table<TS_ZD_Info> TS_ZD_Info
	{
		get
		{
			return this.GetTable<TS_ZD_Info>();
		}
	}
	
	public System.Data.Linq.Table<Jrlx_List> Jrlx_List
	{
		get
		{
			return this.GetTable<Jrlx_List>();
		}
	}
}

[Table(Name="dbo.IP_Bussiness")]
public partial class IP_Bussiness : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _ID;
	
	private string _Bussiness_code;
	
	private string _Line_code;
	
	private string _jrsb;
	
	private string _sbbh;
	
	private string _sbmc;
	
	private string _xqjrwg;
	
	private string _ywlx;
	
	private string _khbh;
	
	private string _khmc;
	
	private string _khlxr;
	
	private string _lxdh;
	
	private string _khlx;
	
	private string _fgqdk;
	
	private string _VPN;
	
	private string _gcjx;
	
	private string _gqtx;
	
	private string _gsfq;
	
	private string _gsfqdk;
	
	private string _sfqxh;
	
	private string _ht_VPN;
	
	private string _VLAN;
	
	private string _brandwidth;
	
	private string _remark;
	
	private string _by1;
	
	private System.Nullable<int> _state;
	
	private string _pzr;
	
	private string _pzsj;
	
	private string _khdz;
	
	private string _jrlyq;
	
	private string _jrjhj;
	
	private string _jrjhjdk;
	
	private string _jrdmc;
	
	private string _yhzyipwg;
	
	private string _yhlywd;
	
	private string _VLAN_name;
	
	private string _dksl;
	
	private string _gqsfqdk;
	
	private string _jrlyqdk;
	
	private string _yhlyqdz;
	
	private string _VPN_Name;
	
	private string _jrdk;
	
	private string _maconu;
	
	private string _dldw;
	
	private string _jfipdz;
	
	private string _voipgw;
	
	private string _pvcid;
	
	private string _bdjfvlan;
	
	private string _ddjfvlan;
	
	private string _ddsbbh;
	
	private string _ddsbmc;
	
	private string _ddsbdk;
	
	private string _macid;
	
	private string _dd_macid;
	
	private string _sbpzxx;
	
	private string _Sbdkhid;
	
	private string _ddsbdkhid;
	
	private string _gjsj;
	
	private string _gjremark;
	
	private string _LjjfID;
	
	private string _DdLjjfID;
	
	private string _Ssqy;
	
	private System.Nullable<long> _Csts;
	
	private string _Cjr;
	
	private string _Cjrq;
	
	private string _Cssj;
	
	private string _issend;
	
	private string _OUNdk_Dd;
	
	private string _glYwONULsh;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnBussiness_codeChanging(string value);
    partial void OnBussiness_codeChanged();
    partial void OnLine_codeChanging(string value);
    partial void OnLine_codeChanged();
    partial void OnjrsbChanging(string value);
    partial void OnjrsbChanged();
    partial void OnsbbhChanging(string value);
    partial void OnsbbhChanged();
    partial void OnsbmcChanging(string value);
    partial void OnsbmcChanged();
    partial void OnxqjrwgChanging(string value);
    partial void OnxqjrwgChanged();
    partial void OnywlxChanging(string value);
    partial void OnywlxChanged();
    partial void OnkhbhChanging(string value);
    partial void OnkhbhChanged();
    partial void OnkhmcChanging(string value);
    partial void OnkhmcChanged();
    partial void OnkhlxrChanging(string value);
    partial void OnkhlxrChanged();
    partial void OnlxdhChanging(string value);
    partial void OnlxdhChanged();
    partial void OnkhlxChanging(string value);
    partial void OnkhlxChanged();
    partial void OnfgqdkChanging(string value);
    partial void OnfgqdkChanged();
    partial void OnVPNChanging(string value);
    partial void OnVPNChanged();
    partial void OngcjxChanging(string value);
    partial void OngcjxChanged();
    partial void OngqtxChanging(string value);
    partial void OngqtxChanged();
    partial void OngsfqChanging(string value);
    partial void OngsfqChanged();
    partial void OngsfqdkChanging(string value);
    partial void OngsfqdkChanged();
    partial void OnsfqxhChanging(string value);
    partial void OnsfqxhChanged();
    partial void Onht_VPNChanging(string value);
    partial void Onht_VPNChanged();
    partial void OnVLANChanging(string value);
    partial void OnVLANChanged();
    partial void OnbrandwidthChanging(string value);
    partial void OnbrandwidthChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void Onby1Changing(string value);
    partial void Onby1Changed();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    partial void OnpzrChanging(string value);
    partial void OnpzrChanged();
    partial void OnpzsjChanging(string value);
    partial void OnpzsjChanged();
    partial void OnkhdzChanging(string value);
    partial void OnkhdzChanged();
    partial void OnjrlyqChanging(string value);
    partial void OnjrlyqChanged();
    partial void OnjrjhjChanging(string value);
    partial void OnjrjhjChanged();
    partial void OnjrjhjdkChanging(string value);
    partial void OnjrjhjdkChanged();
    partial void OnjrdmcChanging(string value);
    partial void OnjrdmcChanged();
    partial void OnyhzyipwgChanging(string value);
    partial void OnyhzyipwgChanged();
    partial void OnyhlywdChanging(string value);
    partial void OnyhlywdChanged();
    partial void OnVLAN_nameChanging(string value);
    partial void OnVLAN_nameChanged();
    partial void OndkslChanging(string value);
    partial void OndkslChanged();
    partial void OngqsfqdkChanging(string value);
    partial void OngqsfqdkChanged();
    partial void OnjrlyqdkChanging(string value);
    partial void OnjrlyqdkChanged();
    partial void OnyhlyqdzChanging(string value);
    partial void OnyhlyqdzChanged();
    partial void OnVPN_NameChanging(string value);
    partial void OnVPN_NameChanged();
    partial void OnjrdkChanging(string value);
    partial void OnjrdkChanged();
    partial void OnmaconuChanging(string value);
    partial void OnmaconuChanged();
    partial void OndldwChanging(string value);
    partial void OndldwChanged();
    partial void OnjfipdzChanging(string value);
    partial void OnjfipdzChanged();
    partial void OnvoipgwChanging(string value);
    partial void OnvoipgwChanged();
    partial void OnpvcidChanging(string value);
    partial void OnpvcidChanged();
    partial void OnbdjfvlanChanging(string value);
    partial void OnbdjfvlanChanged();
    partial void OnddjfvlanChanging(string value);
    partial void OnddjfvlanChanged();
    partial void OnddsbbhChanging(string value);
    partial void OnddsbbhChanged();
    partial void OnddsbmcChanging(string value);
    partial void OnddsbmcChanged();
    partial void OnddsbdkChanging(string value);
    partial void OnddsbdkChanged();
    partial void OnmacidChanging(string value);
    partial void OnmacidChanged();
    partial void Ondd_macidChanging(string value);
    partial void Ondd_macidChanged();
    partial void OnsbpzxxChanging(string value);
    partial void OnsbpzxxChanged();
    partial void OnSbdkhidChanging(string value);
    partial void OnSbdkhidChanged();
    partial void OnddsbdkhidChanging(string value);
    partial void OnddsbdkhidChanged();
    partial void OngjsjChanging(string value);
    partial void OngjsjChanged();
    partial void OngjremarkChanging(string value);
    partial void OngjremarkChanged();
    partial void OnLjjfIDChanging(string value);
    partial void OnLjjfIDChanged();
    partial void OnDdLjjfIDChanging(string value);
    partial void OnDdLjjfIDChanged();
    partial void OnSsqyChanging(string value);
    partial void OnSsqyChanged();
    partial void OnCstsChanging(System.Nullable<long> value);
    partial void OnCstsChanged();
    partial void OnCjrChanging(string value);
    partial void OnCjrChanged();
    partial void OnCjrqChanging(string value);
    partial void OnCjrqChanged();
    partial void OnCssjChanging(string value);
    partial void OnCssjChanged();
    partial void OnissendChanging(string value);
    partial void OnissendChanged();
    partial void OnOUNdk_DdChanging(string value);
    partial void OnOUNdk_DdChanged();
    partial void OnglYwONULshChanging(string value);
    partial void OnglYwONULshChanged();
    #endregion
	
	public IP_Bussiness()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_Bussiness_code", DbType="NVarChar(100)")]
	public string Bussiness_code
	{
		get
		{
			return this._Bussiness_code;
		}
		set
		{
			if ((this._Bussiness_code != value))
			{
				this.OnBussiness_codeChanging(value);
				this.SendPropertyChanging();
				this._Bussiness_code = value;
				this.SendPropertyChanged("Bussiness_code");
				this.OnBussiness_codeChanged();
			}
		}
	}
	
	[Column(Storage="_Line_code", DbType="VarChar(50)")]
	public string Line_code
	{
		get
		{
			return this._Line_code;
		}
		set
		{
			if ((this._Line_code != value))
			{
				this.OnLine_codeChanging(value);
				this.SendPropertyChanging();
				this._Line_code = value;
				this.SendPropertyChanged("Line_code");
				this.OnLine_codeChanged();
			}
		}
	}
	
	[Column(Storage="_jrsb", DbType="VarChar(50)")]
	public string jrsb
	{
		get
		{
			return this._jrsb;
		}
		set
		{
			if ((this._jrsb != value))
			{
				this.OnjrsbChanging(value);
				this.SendPropertyChanging();
				this._jrsb = value;
				this.SendPropertyChanged("jrsb");
				this.OnjrsbChanged();
			}
		}
	}
	
	[Column(Storage="_sbbh", DbType="VarChar(50)")]
	public string sbbh
	{
		get
		{
			return this._sbbh;
		}
		set
		{
			if ((this._sbbh != value))
			{
				this.OnsbbhChanging(value);
				this.SendPropertyChanging();
				this._sbbh = value;
				this.SendPropertyChanged("sbbh");
				this.OnsbbhChanged();
			}
		}
	}
	
	[Column(Storage="_sbmc", DbType="NVarChar(50)")]
	public string sbmc
	{
		get
		{
			return this._sbmc;
		}
		set
		{
			if ((this._sbmc != value))
			{
				this.OnsbmcChanging(value);
				this.SendPropertyChanging();
				this._sbmc = value;
				this.SendPropertyChanged("sbmc");
				this.OnsbmcChanged();
			}
		}
	}
	
	[Column(Storage="_xqjrwg", DbType="VarChar(50)")]
	public string xqjrwg
	{
		get
		{
			return this._xqjrwg;
		}
		set
		{
			if ((this._xqjrwg != value))
			{
				this.OnxqjrwgChanging(value);
				this.SendPropertyChanging();
				this._xqjrwg = value;
				this.SendPropertyChanged("xqjrwg");
				this.OnxqjrwgChanged();
			}
		}
	}
	
	[Column(Storage="_ywlx", DbType="VarChar(50)")]
	public string ywlx
	{
		get
		{
			return this._ywlx;
		}
		set
		{
			if ((this._ywlx != value))
			{
				this.OnywlxChanging(value);
				this.SendPropertyChanging();
				this._ywlx = value;
				this.SendPropertyChanged("ywlx");
				this.OnywlxChanged();
			}
		}
	}
	
	[Column(Storage="_khbh", DbType="VarChar(50)")]
	public string khbh
	{
		get
		{
			return this._khbh;
		}
		set
		{
			if ((this._khbh != value))
			{
				this.OnkhbhChanging(value);
				this.SendPropertyChanging();
				this._khbh = value;
				this.SendPropertyChanged("khbh");
				this.OnkhbhChanged();
			}
		}
	}
	
	[Column(Storage="_khmc", DbType="VarChar(200)")]
	public string khmc
	{
		get
		{
			return this._khmc;
		}
		set
		{
			if ((this._khmc != value))
			{
				this.OnkhmcChanging(value);
				this.SendPropertyChanging();
				this._khmc = value;
				this.SendPropertyChanged("khmc");
				this.OnkhmcChanged();
			}
		}
	}
	
	[Column(Storage="_khlxr", DbType="VarChar(100)")]
	public string khlxr
	{
		get
		{
			return this._khlxr;
		}
		set
		{
			if ((this._khlxr != value))
			{
				this.OnkhlxrChanging(value);
				this.SendPropertyChanging();
				this._khlxr = value;
				this.SendPropertyChanged("khlxr");
				this.OnkhlxrChanged();
			}
		}
	}
	
	[Column(Storage="_lxdh", DbType="VarChar(100)")]
	public string lxdh
	{
		get
		{
			return this._lxdh;
		}
		set
		{
			if ((this._lxdh != value))
			{
				this.OnlxdhChanging(value);
				this.SendPropertyChanging();
				this._lxdh = value;
				this.SendPropertyChanged("lxdh");
				this.OnlxdhChanged();
			}
		}
	}
	
	[Column(Storage="_khlx", DbType="VarChar(50)")]
	public string khlx
	{
		get
		{
			return this._khlx;
		}
		set
		{
			if ((this._khlx != value))
			{
				this.OnkhlxChanging(value);
				this.SendPropertyChanging();
				this._khlx = value;
				this.SendPropertyChanged("khlx");
				this.OnkhlxChanged();
			}
		}
	}
	
	[Column(Storage="_fgqdk", DbType="VarChar(20)")]
	public string fgqdk
	{
		get
		{
			return this._fgqdk;
		}
		set
		{
			if ((this._fgqdk != value))
			{
				this.OnfgqdkChanging(value);
				this.SendPropertyChanging();
				this._fgqdk = value;
				this.SendPropertyChanged("fgqdk");
				this.OnfgqdkChanged();
			}
		}
	}
	
	[Column(Storage="_VPN", DbType="VarChar(50)")]
	public string VPN
	{
		get
		{
			return this._VPN;
		}
		set
		{
			if ((this._VPN != value))
			{
				this.OnVPNChanging(value);
				this.SendPropertyChanging();
				this._VPN = value;
				this.SendPropertyChanged("VPN");
				this.OnVPNChanged();
			}
		}
	}
	
	[Column(Storage="_gcjx", DbType="VarChar(50)")]
	public string gcjx
	{
		get
		{
			return this._gcjx;
		}
		set
		{
			if ((this._gcjx != value))
			{
				this.OngcjxChanging(value);
				this.SendPropertyChanging();
				this._gcjx = value;
				this.SendPropertyChanged("gcjx");
				this.OngcjxChanged();
			}
		}
	}
	
	[Column(Storage="_gqtx", DbType="VarChar(100)")]
	public string gqtx
	{
		get
		{
			return this._gqtx;
		}
		set
		{
			if ((this._gqtx != value))
			{
				this.OngqtxChanging(value);
				this.SendPropertyChanging();
				this._gqtx = value;
				this.SendPropertyChanged("gqtx");
				this.OngqtxChanged();
			}
		}
	}
	
	[Column(Storage="_gsfq", DbType="VarChar(50)")]
	public string gsfq
	{
		get
		{
			return this._gsfq;
		}
		set
		{
			if ((this._gsfq != value))
			{
				this.OngsfqChanging(value);
				this.SendPropertyChanging();
				this._gsfq = value;
				this.SendPropertyChanged("gsfq");
				this.OngsfqChanged();
			}
		}
	}
	
	[Column(Storage="_gsfqdk", DbType="VarChar(50)")]
	public string gsfqdk
	{
		get
		{
			return this._gsfqdk;
		}
		set
		{
			if ((this._gsfqdk != value))
			{
				this.OngsfqdkChanging(value);
				this.SendPropertyChanging();
				this._gsfqdk = value;
				this.SendPropertyChanged("gsfqdk");
				this.OngsfqdkChanged();
			}
		}
	}
	
	[Column(Storage="_sfqxh", DbType="VarChar(50)")]
	public string sfqxh
	{
		get
		{
			return this._sfqxh;
		}
		set
		{
			if ((this._sfqxh != value))
			{
				this.OnsfqxhChanging(value);
				this.SendPropertyChanging();
				this._sfqxh = value;
				this.SendPropertyChanged("sfqxh");
				this.OnsfqxhChanged();
			}
		}
	}
	
	[Column(Storage="_ht_VPN", DbType="VarChar(100)")]
	public string ht_VPN
	{
		get
		{
			return this._ht_VPN;
		}
		set
		{
			if ((this._ht_VPN != value))
			{
				this.Onht_VPNChanging(value);
				this.SendPropertyChanging();
				this._ht_VPN = value;
				this.SendPropertyChanged("ht_VPN");
				this.Onht_VPNChanged();
			}
		}
	}
	
	[Column(Storage="_VLAN", DbType="VarChar(50)")]
	public string VLAN
	{
		get
		{
			return this._VLAN;
		}
		set
		{
			if ((this._VLAN != value))
			{
				this.OnVLANChanging(value);
				this.SendPropertyChanging();
				this._VLAN = value;
				this.SendPropertyChanged("VLAN");
				this.OnVLANChanged();
			}
		}
	}
	
	[Column(Storage="_brandwidth", DbType="VarChar(50)")]
	public string brandwidth
	{
		get
		{
			return this._brandwidth;
		}
		set
		{
			if ((this._brandwidth != value))
			{
				this.OnbrandwidthChanging(value);
				this.SendPropertyChanging();
				this._brandwidth = value;
				this.SendPropertyChanged("brandwidth");
				this.OnbrandwidthChanged();
			}
		}
	}
	
	[Column(Storage="_remark", DbType="VarChar(8000)")]
	public string remark
	{
		get
		{
			return this._remark;
		}
		set
		{
			if ((this._remark != value))
			{
				this.OnremarkChanging(value);
				this.SendPropertyChanging();
				this._remark = value;
				this.SendPropertyChanged("remark");
				this.OnremarkChanged();
			}
		}
	}
	
	[Column(Storage="_by1", DbType="VarChar(200)")]
	public string by1
	{
		get
		{
			return this._by1;
		}
		set
		{
			if ((this._by1 != value))
			{
				this.Onby1Changing(value);
				this.SendPropertyChanging();
				this._by1 = value;
				this.SendPropertyChanged("by1");
				this.Onby1Changed();
			}
		}
	}
	
	[Column(Storage="_state", DbType="Int")]
	public System.Nullable<int> state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[Column(Storage="_pzr", DbType="VarChar(50)")]
	public string pzr
	{
		get
		{
			return this._pzr;
		}
		set
		{
			if ((this._pzr != value))
			{
				this.OnpzrChanging(value);
				this.SendPropertyChanging();
				this._pzr = value;
				this.SendPropertyChanged("pzr");
				this.OnpzrChanged();
			}
		}
	}
	
	[Column(Storage="_pzsj", DbType="VarChar(10)")]
	public string pzsj
	{
		get
		{
			return this._pzsj;
		}
		set
		{
			if ((this._pzsj != value))
			{
				this.OnpzsjChanging(value);
				this.SendPropertyChanging();
				this._pzsj = value;
				this.SendPropertyChanged("pzsj");
				this.OnpzsjChanged();
			}
		}
	}
	
	[Column(Storage="_khdz", DbType="NVarChar(100)")]
	public string khdz
	{
		get
		{
			return this._khdz;
		}
		set
		{
			if ((this._khdz != value))
			{
				this.OnkhdzChanging(value);
				this.SendPropertyChanging();
				this._khdz = value;
				this.SendPropertyChanged("khdz");
				this.OnkhdzChanged();
			}
		}
	}
	
	[Column(Storage="_jrlyq", DbType="VarChar(50)")]
	public string jrlyq
	{
		get
		{
			return this._jrlyq;
		}
		set
		{
			if ((this._jrlyq != value))
			{
				this.OnjrlyqChanging(value);
				this.SendPropertyChanging();
				this._jrlyq = value;
				this.SendPropertyChanged("jrlyq");
				this.OnjrlyqChanged();
			}
		}
	}
	
	[Column(Storage="_jrjhj", DbType="VarChar(50)")]
	public string jrjhj
	{
		get
		{
			return this._jrjhj;
		}
		set
		{
			if ((this._jrjhj != value))
			{
				this.OnjrjhjChanging(value);
				this.SendPropertyChanging();
				this._jrjhj = value;
				this.SendPropertyChanged("jrjhj");
				this.OnjrjhjChanged();
			}
		}
	}
	
	[Column(Storage="_jrjhjdk", DbType="VarChar(50)")]
	public string jrjhjdk
	{
		get
		{
			return this._jrjhjdk;
		}
		set
		{
			if ((this._jrjhjdk != value))
			{
				this.OnjrjhjdkChanging(value);
				this.SendPropertyChanging();
				this._jrjhjdk = value;
				this.SendPropertyChanged("jrjhjdk");
				this.OnjrjhjdkChanged();
			}
		}
	}
	
	[Column(Storage="_jrdmc", DbType="NVarChar(100)")]
	public string jrdmc
	{
		get
		{
			return this._jrdmc;
		}
		set
		{
			if ((this._jrdmc != value))
			{
				this.OnjrdmcChanging(value);
				this.SendPropertyChanging();
				this._jrdmc = value;
				this.SendPropertyChanged("jrdmc");
				this.OnjrdmcChanged();
			}
		}
	}
	
	[Column(Storage="_yhzyipwg", DbType="VarChar(1000)")]
	public string yhzyipwg
	{
		get
		{
			return this._yhzyipwg;
		}
		set
		{
			if ((this._yhzyipwg != value))
			{
				this.OnyhzyipwgChanging(value);
				this.SendPropertyChanging();
				this._yhzyipwg = value;
				this.SendPropertyChanged("yhzyipwg");
				this.OnyhzyipwgChanged();
			}
		}
	}
	
	[Column(Storage="_yhlywd", DbType="VarChar(225)")]
	public string yhlywd
	{
		get
		{
			return this._yhlywd;
		}
		set
		{
			if ((this._yhlywd != value))
			{
				this.OnyhlywdChanging(value);
				this.SendPropertyChanging();
				this._yhlywd = value;
				this.SendPropertyChanged("yhlywd");
				this.OnyhlywdChanged();
			}
		}
	}
	
	[Column(Storage="_VLAN_name", DbType="VarChar(50)")]
	public string VLAN_name
	{
		get
		{
			return this._VLAN_name;
		}
		set
		{
			if ((this._VLAN_name != value))
			{
				this.OnVLAN_nameChanging(value);
				this.SendPropertyChanging();
				this._VLAN_name = value;
				this.SendPropertyChanged("VLAN_name");
				this.OnVLAN_nameChanged();
			}
		}
	}
	
	[Column(Storage="_dksl", DbType="VarChar(50)")]
	public string dksl
	{
		get
		{
			return this._dksl;
		}
		set
		{
			if ((this._dksl != value))
			{
				this.OndkslChanging(value);
				this.SendPropertyChanging();
				this._dksl = value;
				this.SendPropertyChanged("dksl");
				this.OndkslChanged();
			}
		}
	}
	
	[Column(Storage="_gqsfqdk", DbType="VarChar(50)")]
	public string gqsfqdk
	{
		get
		{
			return this._gqsfqdk;
		}
		set
		{
			if ((this._gqsfqdk != value))
			{
				this.OngqsfqdkChanging(value);
				this.SendPropertyChanging();
				this._gqsfqdk = value;
				this.SendPropertyChanged("gqsfqdk");
				this.OngqsfqdkChanged();
			}
		}
	}
	
	[Column(Storage="_jrlyqdk", DbType="VarChar(50)")]
	public string jrlyqdk
	{
		get
		{
			return this._jrlyqdk;
		}
		set
		{
			if ((this._jrlyqdk != value))
			{
				this.OnjrlyqdkChanging(value);
				this.SendPropertyChanging();
				this._jrlyqdk = value;
				this.SendPropertyChanged("jrlyqdk");
				this.OnjrlyqdkChanged();
			}
		}
	}
	
	[Column(Storage="_yhlyqdz", DbType="VarChar(50)")]
	public string yhlyqdz
	{
		get
		{
			return this._yhlyqdz;
		}
		set
		{
			if ((this._yhlyqdz != value))
			{
				this.OnyhlyqdzChanging(value);
				this.SendPropertyChanging();
				this._yhlyqdz = value;
				this.SendPropertyChanged("yhlyqdz");
				this.OnyhlyqdzChanged();
			}
		}
	}
	
	[Column(Storage="_VPN_Name", DbType="VarChar(50)")]
	public string VPN_Name
	{
		get
		{
			return this._VPN_Name;
		}
		set
		{
			if ((this._VPN_Name != value))
			{
				this.OnVPN_NameChanging(value);
				this.SendPropertyChanging();
				this._VPN_Name = value;
				this.SendPropertyChanged("VPN_Name");
				this.OnVPN_NameChanged();
			}
		}
	}
	
	[Column(Storage="_jrdk", DbType="VarChar(50)")]
	public string jrdk
	{
		get
		{
			return this._jrdk;
		}
		set
		{
			if ((this._jrdk != value))
			{
				this.OnjrdkChanging(value);
				this.SendPropertyChanging();
				this._jrdk = value;
				this.SendPropertyChanged("jrdk");
				this.OnjrdkChanged();
			}
		}
	}
	
	[Column(Storage="_maconu", DbType="NVarChar(50)")]
	public string maconu
	{
		get
		{
			return this._maconu;
		}
		set
		{
			if ((this._maconu != value))
			{
				this.OnmaconuChanging(value);
				this.SendPropertyChanging();
				this._maconu = value;
				this.SendPropertyChanged("maconu");
				this.OnmaconuChanged();
			}
		}
	}
	
	[Column(Storage="_dldw", DbType="NVarChar(100)")]
	public string dldw
	{
		get
		{
			return this._dldw;
		}
		set
		{
			if ((this._dldw != value))
			{
				this.OndldwChanging(value);
				this.SendPropertyChanging();
				this._dldw = value;
				this.SendPropertyChanged("dldw");
				this.OndldwChanged();
			}
		}
	}
	
	[Column(Storage="_jfipdz", DbType="VarChar(300)")]
	public string jfipdz
	{
		get
		{
			return this._jfipdz;
		}
		set
		{
			if ((this._jfipdz != value))
			{
				this.OnjfipdzChanging(value);
				this.SendPropertyChanging();
				this._jfipdz = value;
				this.SendPropertyChanged("jfipdz");
				this.OnjfipdzChanged();
			}
		}
	}
	
	[Column(Storage="_voipgw", DbType="VarChar(300)")]
	public string voipgw
	{
		get
		{
			return this._voipgw;
		}
		set
		{
			if ((this._voipgw != value))
			{
				this.OnvoipgwChanging(value);
				this.SendPropertyChanging();
				this._voipgw = value;
				this.SendPropertyChanged("voipgw");
				this.OnvoipgwChanged();
			}
		}
	}
	
	[Column(Storage="_pvcid", DbType="VarChar(50)")]
	public string pvcid
	{
		get
		{
			return this._pvcid;
		}
		set
		{
			if ((this._pvcid != value))
			{
				this.OnpvcidChanging(value);
				this.SendPropertyChanging();
				this._pvcid = value;
				this.SendPropertyChanged("pvcid");
				this.OnpvcidChanged();
			}
		}
	}
	
	[Column(Storage="_bdjfvlan", DbType="VarChar(200)")]
	public string bdjfvlan
	{
		get
		{
			return this._bdjfvlan;
		}
		set
		{
			if ((this._bdjfvlan != value))
			{
				this.OnbdjfvlanChanging(value);
				this.SendPropertyChanging();
				this._bdjfvlan = value;
				this.SendPropertyChanged("bdjfvlan");
				this.OnbdjfvlanChanged();
			}
		}
	}
	
	[Column(Storage="_ddjfvlan", DbType="VarChar(200)")]
	public string ddjfvlan
	{
		get
		{
			return this._ddjfvlan;
		}
		set
		{
			if ((this._ddjfvlan != value))
			{
				this.OnddjfvlanChanging(value);
				this.SendPropertyChanging();
				this._ddjfvlan = value;
				this.SendPropertyChanged("ddjfvlan");
				this.OnddjfvlanChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbbh", DbType="VarChar(50)")]
	public string ddsbbh
	{
		get
		{
			return this._ddsbbh;
		}
		set
		{
			if ((this._ddsbbh != value))
			{
				this.OnddsbbhChanging(value);
				this.SendPropertyChanging();
				this._ddsbbh = value;
				this.SendPropertyChanged("ddsbbh");
				this.OnddsbbhChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbmc", DbType="NVarChar(50)")]
	public string ddsbmc
	{
		get
		{
			return this._ddsbmc;
		}
		set
		{
			if ((this._ddsbmc != value))
			{
				this.OnddsbmcChanging(value);
				this.SendPropertyChanging();
				this._ddsbmc = value;
				this.SendPropertyChanged("ddsbmc");
				this.OnddsbmcChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbdk", DbType="VarChar(50)")]
	public string ddsbdk
	{
		get
		{
			return this._ddsbdk;
		}
		set
		{
			if ((this._ddsbdk != value))
			{
				this.OnddsbdkChanging(value);
				this.SendPropertyChanging();
				this._ddsbdk = value;
				this.SendPropertyChanged("ddsbdk");
				this.OnddsbdkChanged();
			}
		}
	}
	
	[Column(Storage="_macid", DbType="VarChar(20)")]
	public string macid
	{
		get
		{
			return this._macid;
		}
		set
		{
			if ((this._macid != value))
			{
				this.OnmacidChanging(value);
				this.SendPropertyChanging();
				this._macid = value;
				this.SendPropertyChanged("macid");
				this.OnmacidChanged();
			}
		}
	}
	
	[Column(Storage="_dd_macid", DbType="VarChar(20)")]
	public string dd_macid
	{
		get
		{
			return this._dd_macid;
		}
		set
		{
			if ((this._dd_macid != value))
			{
				this.Ondd_macidChanging(value);
				this.SendPropertyChanging();
				this._dd_macid = value;
				this.SendPropertyChanged("dd_macid");
				this.Ondd_macidChanged();
			}
		}
	}
	
	[Column(Storage="_sbpzxx", DbType="NVarChar(200)")]
	public string sbpzxx
	{
		get
		{
			return this._sbpzxx;
		}
		set
		{
			if ((this._sbpzxx != value))
			{
				this.OnsbpzxxChanging(value);
				this.SendPropertyChanging();
				this._sbpzxx = value;
				this.SendPropertyChanged("sbpzxx");
				this.OnsbpzxxChanged();
			}
		}
	}
	
	[Column(Storage="_Sbdkhid", DbType="NVarChar(20)")]
	public string Sbdkhid
	{
		get
		{
			return this._Sbdkhid;
		}
		set
		{
			if ((this._Sbdkhid != value))
			{
				this.OnSbdkhidChanging(value);
				this.SendPropertyChanging();
				this._Sbdkhid = value;
				this.SendPropertyChanged("Sbdkhid");
				this.OnSbdkhidChanged();
			}
		}
	}
	
	[Column(Storage="_ddsbdkhid", DbType="NVarChar(20)")]
	public string ddsbdkhid
	{
		get
		{
			return this._ddsbdkhid;
		}
		set
		{
			if ((this._ddsbdkhid != value))
			{
				this.OnddsbdkhidChanging(value);
				this.SendPropertyChanging();
				this._ddsbdkhid = value;
				this.SendPropertyChanged("ddsbdkhid");
				this.OnddsbdkhidChanged();
			}
		}
	}
	
	[Column(Storage="_gjsj", DbType="VarChar(10)")]
	public string gjsj
	{
		get
		{
			return this._gjsj;
		}
		set
		{
			if ((this._gjsj != value))
			{
				this.OngjsjChanging(value);
				this.SendPropertyChanging();
				this._gjsj = value;
				this.SendPropertyChanged("gjsj");
				this.OngjsjChanged();
			}
		}
	}
	
	[Column(Storage="_gjremark", DbType="NVarChar(4000)")]
	public string gjremark
	{
		get
		{
			return this._gjremark;
		}
		set
		{
			if ((this._gjremark != value))
			{
				this.OngjremarkChanging(value);
				this.SendPropertyChanging();
				this._gjremark = value;
				this.SendPropertyChanged("gjremark");
				this.OngjremarkChanged();
			}
		}
	}
	
	[Column(Storage="_LjjfID", DbType="VarChar(50)")]
	public string LjjfID
	{
		get
		{
			return this._LjjfID;
		}
		set
		{
			if ((this._LjjfID != value))
			{
				this.OnLjjfIDChanging(value);
				this.SendPropertyChanging();
				this._LjjfID = value;
				this.SendPropertyChanged("LjjfID");
				this.OnLjjfIDChanged();
			}
		}
	}
	
	[Column(Storage="_DdLjjfID", DbType="VarChar(50)")]
	public string DdLjjfID
	{
		get
		{
			return this._DdLjjfID;
		}
		set
		{
			if ((this._DdLjjfID != value))
			{
				this.OnDdLjjfIDChanging(value);
				this.SendPropertyChanging();
				this._DdLjjfID = value;
				this.SendPropertyChanged("DdLjjfID");
				this.OnDdLjjfIDChanged();
			}
		}
	}
	
	[Column(Storage="_Ssqy", DbType="NVarChar(50)")]
	public string Ssqy
	{
		get
		{
			return this._Ssqy;
		}
		set
		{
			if ((this._Ssqy != value))
			{
				this.OnSsqyChanging(value);
				this.SendPropertyChanging();
				this._Ssqy = value;
				this.SendPropertyChanged("Ssqy");
				this.OnSsqyChanged();
			}
		}
	}
	
	[Column(Storage="_Csts", DbType="BigInt")]
	public System.Nullable<long> Csts
	{
		get
		{
			return this._Csts;
		}
		set
		{
			if ((this._Csts != value))
			{
				this.OnCstsChanging(value);
				this.SendPropertyChanging();
				this._Csts = value;
				this.SendPropertyChanged("Csts");
				this.OnCstsChanged();
			}
		}
	}
	
	[Column(Storage="_Cjr", DbType="NVarChar(50)")]
	public string Cjr
	{
		get
		{
			return this._Cjr;
		}
		set
		{
			if ((this._Cjr != value))
			{
				this.OnCjrChanging(value);
				this.SendPropertyChanging();
				this._Cjr = value;
				this.SendPropertyChanged("Cjr");
				this.OnCjrChanged();
			}
		}
	}
	
	[Column(Storage="_Cjrq", DbType="VarChar(25)")]
	public string Cjrq
	{
		get
		{
			return this._Cjrq;
		}
		set
		{
			if ((this._Cjrq != value))
			{
				this.OnCjrqChanging(value);
				this.SendPropertyChanging();
				this._Cjrq = value;
				this.SendPropertyChanged("Cjrq");
				this.OnCjrqChanged();
			}
		}
	}
	
	[Column(Storage="_Cssj", DbType="VarChar(25)")]
	public string Cssj
	{
		get
		{
			return this._Cssj;
		}
		set
		{
			if ((this._Cssj != value))
			{
				this.OnCssjChanging(value);
				this.SendPropertyChanging();
				this._Cssj = value;
				this.SendPropertyChanged("Cssj");
				this.OnCssjChanged();
			}
		}
	}
	
	[Column(Storage="_issend", DbType="VarChar(25)")]
	public string issend
	{
		get
		{
			return this._issend;
		}
		set
		{
			if ((this._issend != value))
			{
				this.OnissendChanging(value);
				this.SendPropertyChanging();
				this._issend = value;
				this.SendPropertyChanged("issend");
				this.OnissendChanged();
			}
		}
	}
	
	[Column(Storage="_OUNdk_Dd", DbType="NVarChar(1000)")]
	public string OUNdk_Dd
	{
		get
		{
			return this._OUNdk_Dd;
		}
		set
		{
			if ((this._OUNdk_Dd != value))
			{
				this.OnOUNdk_DdChanging(value);
				this.SendPropertyChanging();
				this._OUNdk_Dd = value;
				this.SendPropertyChanged("OUNdk_Dd");
				this.OnOUNdk_DdChanged();
			}
		}
	}
	
	[Column(Storage="_glYwONULsh", DbType="NVarChar(50)")]
	public string glYwONULsh
	{
		get
		{
			return this._glYwONULsh;
		}
		set
		{
			if ((this._glYwONULsh != value))
			{
				this.OnglYwONULshChanging(value);
				this.SendPropertyChanging();
				this._glYwONULsh = value;
				this.SendPropertyChanged("glYwONULsh");
				this.OnglYwONULshChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.TS_ZD_Info")]
public partial class TS_ZD_Info
{
	
	private string _type;
	
	private string _lsh;
	
	private string _mc;
	
	private string _code;
	
	private string _bz;
	
	private string _czj;
	
	private string _czrq;
	
	private System.Nullable<bool> _tag;
	
	private string _flag;
	
	private string _YwlbLsh;
	
	private System.Nullable<int> _Sfxs;
	
	private string _Color;
	
	private System.Nullable<long> _xh;
	
	public TS_ZD_Info()
	{
	}
	
	[Column(Storage="_type", DbType="VarChar(50)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this._type = value;
			}
		}
	}
	
	[Column(Storage="_lsh", DbType="VarChar(20)")]
	public string lsh
	{
		get
		{
			return this._lsh;
		}
		set
		{
			if ((this._lsh != value))
			{
				this._lsh = value;
			}
		}
	}
	
	[Column(Storage="_mc", DbType="VarChar(100)")]
	public string mc
	{
		get
		{
			return this._mc;
		}
		set
		{
			if ((this._mc != value))
			{
				this._mc = value;
			}
		}
	}
	
	[Column(Storage="_code", DbType="VarChar(100)")]
	public string code
	{
		get
		{
			return this._code;
		}
		set
		{
			if ((this._code != value))
			{
				this._code = value;
			}
		}
	}
	
	[Column(Storage="_bz", DbType="VarChar(100)")]
	public string bz
	{
		get
		{
			return this._bz;
		}
		set
		{
			if ((this._bz != value))
			{
				this._bz = value;
			}
		}
	}
	
	[Column(Storage="_czj", DbType="VarChar(20)")]
	public string czj
	{
		get
		{
			return this._czj;
		}
		set
		{
			if ((this._czj != value))
			{
				this._czj = value;
			}
		}
	}
	
	[Column(Storage="_czrq", DbType="VarChar(20)")]
	public string czrq
	{
		get
		{
			return this._czrq;
		}
		set
		{
			if ((this._czrq != value))
			{
				this._czrq = value;
			}
		}
	}
	
	[Column(Storage="_tag", DbType="Bit")]
	public System.Nullable<bool> tag
	{
		get
		{
			return this._tag;
		}
		set
		{
			if ((this._tag != value))
			{
				this._tag = value;
			}
		}
	}
	
	[Column(Storage="_flag", DbType="VarChar(5)")]
	public string flag
	{
		get
		{
			return this._flag;
		}
		set
		{
			if ((this._flag != value))
			{
				this._flag = value;
			}
		}
	}
	
	[Column(Storage="_YwlbLsh", DbType="NVarChar(50)")]
	public string YwlbLsh
	{
		get
		{
			return this._YwlbLsh;
		}
		set
		{
			if ((this._YwlbLsh != value))
			{
				this._YwlbLsh = value;
			}
		}
	}
	
	[Column(Storage="_Sfxs", DbType="Int")]
	public System.Nullable<int> Sfxs
	{
		get
		{
			return this._Sfxs;
		}
		set
		{
			if ((this._Sfxs != value))
			{
				this._Sfxs = value;
			}
		}
	}
	
	[Column(Storage="_Color", DbType="NVarChar(50)")]
	public string Color
	{
		get
		{
			return this._Color;
		}
		set
		{
			if ((this._Color != value))
			{
				this._Color = value;
			}
		}
	}
	
	[Column(Storage="_xh", DbType="BigInt")]
	public System.Nullable<long> xh
	{
		get
		{
			return this._xh;
		}
		set
		{
			if ((this._xh != value))
			{
				this._xh = value;
			}
		}
	}
}

[Table(Name="dbo.Jrlx_List")]
public partial class Jrlx_List : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _nodeid;
	
	private string _parentid;
	
	private string _nodename;
	
	private string _form;
	
	private System.Nullable<int> _showorder;
	
	private string _bz;
	
	private System.Nullable<int> _bmgzID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnodeidChanging(string value);
    partial void OnnodeidChanged();
    partial void OnparentidChanging(string value);
    partial void OnparentidChanged();
    partial void OnnodenameChanging(string value);
    partial void OnnodenameChanged();
    partial void OnformChanging(string value);
    partial void OnformChanged();
    partial void OnshoworderChanging(System.Nullable<int> value);
    partial void OnshoworderChanged();
    partial void OnbzChanging(string value);
    partial void OnbzChanged();
    partial void OnbmgzIDChanging(System.Nullable<int> value);
    partial void OnbmgzIDChanged();
    #endregion
	
	public Jrlx_List()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_nodeid", DbType="VarChar(20)")]
	public string nodeid
	{
		get
		{
			return this._nodeid;
		}
		set
		{
			if ((this._nodeid != value))
			{
				this.OnnodeidChanging(value);
				this.SendPropertyChanging();
				this._nodeid = value;
				this.SendPropertyChanged("nodeid");
				this.OnnodeidChanged();
			}
		}
	}
	
	[Column(Storage="_parentid", DbType="VarChar(20)")]
	public string parentid
	{
		get
		{
			return this._parentid;
		}
		set
		{
			if ((this._parentid != value))
			{
				this.OnparentidChanging(value);
				this.SendPropertyChanging();
				this._parentid = value;
				this.SendPropertyChanged("parentid");
				this.OnparentidChanged();
			}
		}
	}
	
	[Column(Storage="_nodename", DbType="NVarChar(50)")]
	public string nodename
	{
		get
		{
			return this._nodename;
		}
		set
		{
			if ((this._nodename != value))
			{
				this.OnnodenameChanging(value);
				this.SendPropertyChanging();
				this._nodename = value;
				this.SendPropertyChanged("nodename");
				this.OnnodenameChanged();
			}
		}
	}
	
	[Column(Storage="_form", DbType="NVarChar(100)")]
	public string form
	{
		get
		{
			return this._form;
		}
		set
		{
			if ((this._form != value))
			{
				this.OnformChanging(value);
				this.SendPropertyChanging();
				this._form = value;
				this.SendPropertyChanged("form");
				this.OnformChanged();
			}
		}
	}
	
	[Column(Storage="_showorder", DbType="Int")]
	public System.Nullable<int> showorder
	{
		get
		{
			return this._showorder;
		}
		set
		{
			if ((this._showorder != value))
			{
				this.OnshoworderChanging(value);
				this.SendPropertyChanging();
				this._showorder = value;
				this.SendPropertyChanged("showorder");
				this.OnshoworderChanged();
			}
		}
	}
	
	[Column(Storage="_bz", DbType="NVarChar(100)")]
	public string bz
	{
		get
		{
			return this._bz;
		}
		set
		{
			if ((this._bz != value))
			{
				this.OnbzChanging(value);
				this.SendPropertyChanging();
				this._bz = value;
				this.SendPropertyChanged("bz");
				this.OnbzChanged();
			}
		}
	}
	
	[Column(Storage="_bmgzID", DbType="Int")]
	public System.Nullable<int> bmgzID
	{
		get
		{
			return this._bmgzID;
		}
		set
		{
			if ((this._bmgzID != value))
			{
				this.OnbmgzIDChanging(value);
				this.SendPropertyChanging();
				this._bmgzID = value;
				this.SendPropertyChanged("bmgzID");
				this.OnbmgzIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
